NOTES  90 degree bends with wire
The 90 with wire and labor cost 28% less than a LB.             
Both the materials and the labor are less expesive.             
the factory 90 uses more wire ( and gains some distance )       
 ( Use 380 amps for 400 amps )
                                                                
                                                                
                                                 15.98        12.78             
                                                  3.19         2.13             
                                              4,097.23                          
                                              2,876.40     1,005.73             
                                              1,220.83       610.43             
                                                  0.00         0.00             
                                                  0.00                          
                                                                
                                                                

The cost of a 90 degree bend for various sizes


420A  Use 320A                
                1 ALRC-90  3-in                                 2.00      443.68          
                5 THHN    600MCM                                0.24      103.05          
                1 NT-CON  3-in                                  0.75      307.05
                                                                2.99     $853.78          

380A  400  3-1/2
                1 ALRC-90  3-in                                 2.00      443.68          
                5 THHN    500mcm                                0.22       87.25          
                1 NT-CON  3-in                                  0.75      307.05
                                                                2.97     $837.98          

335A  350
                1 ALRC-90  2-1/2                                1.50      324.17          
                5 THHN    400mcm                                0.20       79.55          
                1 NT-CON  2-1/2                                 0.60      224.40
                                                                2.30     $628.12          

285A  300 CB
                1 ALRC-90  2-in                                 0.95      203.14          
                5 THHN    300mcm                                0.17       61.80          
                1 NT-CON  2-IN                                  0.40      115.00
                                                                1.52     $379.94          

200A  200
                1 ALRC-90  1-1/2                                0.75      156.83          
                5 THHN    3/0                                   0.13       58.20          
                1 NT-CON  1-1/2                                 0.30       72.64
                                                                1.18     $287.67          

150A  150
                1 ALRC-90  1-1/4                                0.60      124.41          
                5 THHN    1/0                                   0.11       32.60          
                1 NT-CON  1-1/4                                 0.25       64.16
                                                                0.96     $221.17          

130A  125
                1 ALRC-90  1-1/4                                0.60      124.41          
                5 THHN    #1                                    0.10       37.40          
                1 NT-CON  1-1/4                                 0.25       64.16
                                                                0.95     $225.97          

115A  100
                1 ALRC-90  1-in                                 0.50      100.32          
                5 THHN    #2                                    0.09       30.90          
                1 NT-CON  1-IN                                  0.16       36.52
                                                                0.75     $167.74          

85A    90
                1 ALRC-90  1-in                                 0.50      100.32          
                5 THHN    #4                                    0.07       22.75          
                1 NT-CON  1-in                                  0.16       36.52
                                                                0.73     $159.59          

65A    70
                1 ALRC-90  3/4                                  0.40       79.41          
                5 THHN    #6                                    0.06       16.10          
                1 NT-CON  3/4                                   0.14       30.46
                                                                0.60     $125.97          

50A    50
                1 ALRC-90  1/2                                  0.35       68.45          
                5 THHN    #8                                    0.05       12.60          
                1 NT-CON  1/2                                   0.12       24.90
                                                                0.52     $105.95          

30A    30
                1 ALRC-90  1/2                                  0.35       68.45          
                5 THHN    #10                                   0.04       10.00          
                1 NT-CON  1/2                                   0.12       24.90
                                                                0.51     $103.35          

Total Estimate                                                         $4,097.23                    


\ SO INDEX
: 420A              263.58 EXD     2.99 Hrs ; \
: 380A              237.43         2.97
: 335A              181.06         2.30
: 285A               81.87         1.52
: 200A               46.67         1.18
: 150A               33.95         0.96
: 130A               29.10         0.95
: 115A               20.07         0.75
: 85A                17.02         0.73
: 65A                11.74         0.60
: 50A                 9.20         0.52
: 30A                 8.20         0.51


