NOTES  90 degree bends with wire
The 90 with wire and labor cost 28% less than a LB.             
Both the materials and the labor are less expesive.             
the factory 90 uses more wire ( and gains some distance )       
 ( Use 380 amps for 400 amps )
                                                                
                                                                
                                                  5.72         4.57
                                                  1.14         0.76
                                              1,588.71
                                              1,029.60       360.00
                                                559.11       279.54
                                                  0.00         0.00
                                                  0.00
                                                                


Have to put this for extend to work?


420A  Use 320A
                1 ALRC-90  3-in                                 2.00      443.68
                5 THHN    600-MCM
                1 NT-CON  3-in


380A  400  3-1/2
                1 ALRC-90  3-in
                5 THHN    500mcm
                1 NT-CON  3-in


\ 335A  350
                1 ALRC-90  2-1/2
                5 THHN    400mcm
                1 NT-CON  2-1/2


\ 285A  300
                1 ALRC-90  2-in
                5 THHN    300mcm
                1 NT-CON  2-IN


\ 200A  200
                1 ALRC-90  1-1/2
                5 THHN    3/0
                1 NT-CON  1-1/2


\ 150A  150
                1 ALRC-90  1-1/4
                5 THHN    1/0
                1 NT-CON  1-1/4


\ 130A  125
                1 ALRC-90  1-1/4
                5 THHN    #1
                1 NT-CON  1-1/4


\ 115A  100
                1 ALRC-90  1-in
                5 THHN    #2
                1 NT-CON  1-IN


\ 85A    90
                1 ALRC-90  1-in
                5 THHN    #4
                1 NT-CON  1-in


\ 65A    70
                1 ALRC-90  3/4
                5 THHN    #6
                1 NT-CON  3/4


\ 50A    50
                1 ALRC-90  1/2
                5 THHN    #8
                1 NT-CON  1/2


\ 30A    30
                1 ALRC-90  1/2
                5 THHN    #10
                1 NT-CON  1/2


Total Estimate

                                               
\ SO INDEX                                      
: 420A              263.58 EXD     2.99 Hrs ; \ 
: 380A              237.43         2.97        3
: 335A              181.06         2.30        2
: 285A               81.87         1.52        1
: 200A               46.67         1.18        1
: 150A               33.95         0.96         
: 130A               29.10         0.95         
: 115A               20.07         0.75         
: 85A                17.02         0.73         
: 65A                11.74         0.60         
: 50A                 9.20         0.52         
: 30A                 8.20         0.51         
                                                
                                                
Total Estimate                                                             $0.00

