NOTES  90 degree bends with wire                                
The 90 with wire and labor cost 28% less than a LB.             
Both the materials and the labor are less expesive.             
the factory 90 uses more wire ( and gains some distance )       
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 420A  Use 320A             
                1 ALRC-90  3-in                
                5 THHN    600mcm               
                1 NT-CON  3-in                 
                                               
                ( Use 380 amps for 400 amps )  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 380A  400  3-1/2           
                1 ALRC-90  3-in                
                5 THHN    500mcm               
                1 NT-CON  3-in                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 335A  350                  
                1 ALRC-90  2-1/2               
                5 THHN    400mcm               
                1 NT-CON  2-1/2                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 285A  300                  
                1 ALRC-90  2-in                
                5 THHN    300mcm               
                1 NT-CON  2-IN                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 200A  200                  
                1 ALRC-90  1-1/2               
                5 THHN    3/0                  
                1 NT-CON  1-1/2                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 150A  150                  
                1 ALRC-90  1-1/4               
                5 THHN    1/0                  
                1 NT-CON  1-1/4                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 130A  125                  
                1 ALRC-90  1-1/4               
                5 THHN    #1                   
                1 NT-CON  1-1/4                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 115A  100                  
                1 ALRC-90  1-in                
                5 THHN    #2                   
                1 NT-CON  1-IN                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 85A    90                  
                1 ALRC-90  1-in                
                5 THHN    #4                   
                1 NT-CON  1-in                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 65A    70                  
                1 ALRC-90  3/4                 
                5 THHN    #6                   
                1 NT-CON  3/4                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 50A    50                  
                1 ALRC-90  1/2                 
                5 THHN    #8                   
                1 NT-CON  1/2                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 30A    30                  
                1 ALRC-90  1/2                 
                5 THHN    #10                  
                1 NT-CON  1/2                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ SO INDEX                                                   AEC
: 420A              263.58 EXD     2.99 Hrs ; \  ( 404.11 )     
: 380A              237.43         2.97        377.02           
: 335A              181.06         2.30        289.16           
: 285A               81.87         1.52        153.31           
: 200A               46.67         1.18        102.13           
: 150A               33.95         0.96         79.07           
: 130A               29.10         0.95         73.75           
: 115A               20.07         0.75         55.32           
: 85A                17.02         0.73         51.33           
: 65A                11.74         0.60         39.94           
: 50A                 9.20         0.52         33.64           
: 30A                 8.20         0.51         32.17           
                                                                
                                                                
                                                                


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


