The 90 with wire                                    12-12-90 AEC
Both the materials and the labor are less expe                  
the factory 90 uses more wire ( and gains some             0.00 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 420A  Use 320A                                                
                1 EMT-90  3-in                   78.15          
                5 THHN    600mcm                                
                2 SS-COUP 3-in                                  
                                                                
                ( Use 380 amps for 400 amps )                   
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 380A  400A        100.16 +tax     1.14 hrs    149.01          
                1 EMT-90  3-in                   78.15          
                5 THHN    500mcm                 43.10          
                2 SS-COUP  3-in                  27.76   149.01 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 335A               53.34 +tax     1.00 hrs    121.97          
                1 EMT-90  2-1/2                  57.68          
                5 THHN    400mcm                 39.35          
                2 SS-COUP  2-1/2                 24.94   121.97 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 285A               27.17 +tax     0.85 hrs     79.15          
                1 EMT-90  2-in                   34.76          
                5 THHN    300mcm                 29.55          
                2 SS-COUP  2-IN                  14.84    79.15 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 200A               16.77 +tax     0.69 hrs     57.13          
                1 EMT-90  1-1/2                  26.08          
                5 THHN    3/0                    18.65          
                2 SS-COUP  1-1/2                 12.40    57.13 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 150A               12.21 +tax     0.55 hrs     43.93          
                1 EMT-90  1-1/4                  19.81          
                5 THHN    1/0                    14.10          
                2 SS-COUP  1-1/4                 10.02    43.93 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 130A               11.36 +tax     0.54 hrs     42.28          
                1 EMT-90  1-1/4                  19.81          
                5 THHN    #1                     12.45          
                2 SS-COUP  1-1/4                 10.02    42.28 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 115A                8.16 +tax     0.46 hrs     33.96          
                1 EMT-90  1-in                   16.02          
                5 THHN    #2                     10.20          
                2 SS-COUP  1-IN                   7.74    33.96 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 85A                 6.41 +tax     0.44 hrs     30.61          
                1 EMT-90  1-in                   16.02          
                5 THHN    #4                      6.85          
                2 SS-COUP  1-in                   7.74    30.61 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 65A                 2.39 +tax     0.16 hrs     11.18          
                ( EMT-90  3/4                                   
                5 THHN    #6                      5.20          
                2 SS-COUP  3/4                    5.98    11.18 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 50A                 1.69 +tax     0.13 hrs      8.73          
                ( EMT-90  1/2                                   
                5 THHN    #8                      4.15          
                2 SS-COUP  1/2                    4.58     8.73 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 30A                 0.99 +tax     0.12 hrs      7.28          
                ( EMT-90  1/2                                   
                5 THHN    #10                     2.70          
                2 SS-COUP  1/2                    4.58     7.28 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ SO INDEX                                                   AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


