                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


EOF LOAD                                                        
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LF-ALRC 50A                
                100 ALRC 1/2                   
                300 THHN #8                    
                25  NAILER 1/2                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ LF-ALRC 65A                
                100 ALRC 3/4                   
                300 THHN #6                    
                15 STRAP 3/4                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ LF-ALRC 85A                
                100 ALRC 1-IN                  
                300 THHN #4                    
                15 STRAP 1-IN                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ LF-ALRC 115A               
                100 ALRC 1-IN                  
                300 THHN #2                    
                15 STRAP 1-IN                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ LF-ALRC 130A               
                100 ALRC 1-1/4                 
                300 THHN #1                    
                15 STRAP 1-1/4                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ LF-ALRC 150A               
                100 ALRC 1-1/4                 
                300 THHN 1/0                   
                15 STRAP 1-1/4                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ LF-ALRC 200A  100 FT !!    
                100 ALRC 1-1/2                 
                300 THHN 3/0                   
                15 STRAP 1-1/2                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ LF-ALRC 400A  10 FT !!     
                 10 ALRC 3-IN                  
                 30 THHN 500MCM                
                 2 STRAP 3-IN                  
                 ( mult by 10 )                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ SO loader                                                  AEC
Vocabulary LF-ALRC                                              
LF-ALRC Definitions                                             
`             50A       169.46 w/c    8    c ; \    640.25      
`             65A       223.43 w/c   10    c ; \    787.25      
`             85A       328.19 w/c   11    c ; \  1,008.15      
`             115A      432.50 w/c   13    c ; \  1,209.15      
`             130A      566.99 w/c   14    c ; \  1,472.00      
`             150A      616.19 w/c   15    c ; \  1,568.00      
`             200A      826.50 w/c   17    c ; \  1,961.95      
`             400A    2,228.05 w/c   27    c ; \  4,374.10      
Elect                                                           
                                                                
                                                                
                                                                
                                                                


