exp                                                             
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


SW-BOX                2.87 Parts    0.30 hrs     16.97          
                SW-BOX FB                        16.97          
1.69 w/s                                                  16.97 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


4S                                                              
                4S FB                                           
                4S-1G 1/2                                       
2.65 w/s                                                        
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


5S                    9.61 Parts    0.55 hrs     35.46          
                5S FB                            24.39          
                5S-1G 1/2                        11.07    35.46 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


PVC                   0.93 Parts    0.10 hrs      5.63          
.51 w/s         box-pvc 1g                        5.63     5.63 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


mc                   15.60 Parts    0.96 hrs     60.72          
                4 mc 12/2                        10.12          
                20 mc 12/2                       50.60    60.72 
                                                                
40 diff                                                         
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


                      4.51 Parts    0.43 hrs     25.58          
                1 4s vb                          22.79          
                3 mc-con 1/2                      2.79    25.58 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


