Closet lights modules
                                                                
Missing the price for LED strip fixture
                                                                
                                                                
                                                                
                                                                
                                                  5.38         4.30             
                                                  1.07         0.71             
                                              1,230.40                          
                                                968.40       338.60             
                                                262.00       131.00             
                                                  0.00         0.00             
                                                  0.00                          
                                                                
                                                                



Strip
                Neat-EMT                                        0.00        0.00          
                LT-easy                                         1.25      243.00          
                SW-easy                                         1.00      198.00          
                LED-UC 40-inch                                  0.50      240.00
                                                                2.75     $681.00          

Ball
                Neat-EMT                                        0.00        0.00          
                LT-easy                                         1.25      243.00          
                SW-easy                                         1.00      198.00          
                Ball 6-in+string                                0.30       84.00          
                Lamp LED-A19                                    0.08       24.40
                                                                2.63     $549.40          
                                               
Total Estimate                                                         $1,230.40                    

