Closet lights modules
                                                                
Missing the price for LED strip fixture
                                                                
                                                                
                                                                
                                           Experienced     Learning
                                      Hrs         2.63         3.15 Man Hours
                                      Dys         0.32         0.39 Man Days
                                      Tot       549.40              Contract
                                      Lab       473.40       165.52 W/S Labor
                                      Mtl        76.00        38.00 Pre Tax
                                      Oth         0.00         0.00
                                      Pmt         0.00

                                                  2.63         3.15
                                                  0.32         0.39


Closet Ball Light
                Neat-EMT                               0.00     0.00        0.00
                LT-easy                               18.00     1.25      243.00
                SW-easy                               18.00     1.00      198.00
                Ball 6-in+string                      30.00     0.30       84.00
                Lamp LED-A19                          10.00     0.08       24.40
                                                     $76.00     2.63     $549.40

Total Estimate                                                           $549.40

