                                                    89-01-29 AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                  0.89         0.71             
                                                  0.17         0.11             
                                                173.12                          
                                                160.20        56.01             
                                                 12.92         6.46             
                                                  0.00         0.00             
                                                  0.00                          
                                                                




D&P  Decorator      2.11
                1 Deco PR                                       0.25       47.90          
                1 Deco 1-Gang                                   0.05        9.80          
                2 NUT YELLOW                                    0.08       14.56          
                1 THHN #14                                      0.00        0.28
                                                                0.38      $72.54          

D&P  Victorian      2.11
                1 DEVICE PR                                     0.10       20.00          
                1 PLATE PR                                      0.03        6.06          
o               2 NUT YELLOW                                    0.08       14.56          
                1 THHN #14                                      0.00        0.28          
                ( flex loom                                     0.00        0.00
                                                                0.21      $40.90          

D&P  inc Nut        2.03
                1 DEVICE PR                                     0.10       20.00          
                1 PLATE PR                                      0.03        6.06          
erage           1 NUT YELLOW                                    0.04        7.28          
                1 THHN #14                                      0.00        0.28
                                                                0.17      $33.62          

D&P-    Mass        1.87
                1 Device PR                                     0.10       20.00          
                1 Plate PR                                      0.03        6.06
                                                                0.13      $26.06          

When there are a                               
lot of them and                                                 0.00        0.00          
most all of the                                                 0.00        0.00          
outlets are                                                     0.00        0.00          
good like after                                                 0.00        0.00          
smoke damage.                                                   0.00        0.00          
                                               

Device&Plate                                   
                                               
                                               
\ Dish cord           4.80   
                ( Cord connection )            
                1 Molded Cord                  
                1 romex blue                   
                2 nut yellow                   
                                               
                                               
Total Estimate                                                           $173.12                    

