                                                    89-01-29 AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                  0.89         0.71
                                                  0.11         0.08
                                                134.30
                                                121.38        42.44
                                                 12.92         6.46
                                                  0.00         0.00
                                                  0.00
                                                                




D&P  Decorator      2.11
                1 Deco PR                                       0.25       37.00
                1 Deco 1-Gang                                   0.05        7.62
                2 NUT YELLOW                                    0.08       11.07
                1 THHN #14                                      0.00        0.28
                                                                0.38      $55.97

D&P  Victorian      2.11
                1 DEVICE PR                                     0.10       15.64
                1 PLATE PR                                      0.03        4.75
                2 NUT YELLOW                                    0.08       11.07
                1 THHN #14                                      0.00        0.28
                ( flex loom                                     0.00        0.00
                                                                0.21      $31.74

D&P  inc Nut        2.03
                1 DEVICE PR                                     0.10       15.64
                1 PLATE PR                                      0.03        4.75
Average         1 NUT YELLOW                                    0.04        5.53
                1 THHN #14                                      0.00        0.28
                                                                0.17      $26.20

D&P-    Mass        1.87
                1 Device PR                                     0.10       15.64
                1 Plate PR                                      0.03        4.75
                                                                0.13      $20.39

When there are a
lot of them and                                                 0.00        0.00
most all of the                                                 0.00        0.00
outlets are                                                     0.00        0.00
good like after                                                 0.00        0.00
smoke damage.                                                   0.00        0.00


Device&Plate


\ Dish cord           4.80
                ( Cord connection )
                1 Molded Cord
                1 romex blue
                2 nut yellow


Total Estimate                                                           $134.30

