                                                    89-01-29 AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ D&P  Decorator      2.11   
                1 Deco PR                      
                1 Deco 1G                      
                2 NUT YELLOW                   
                1 THHN #14                     
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ D&P  Victorian      2.11   
                1 DEVICE PR                    
                1 PLATE PR                     
Two             2 NUT YELLOW                   
                1 THHN #14                     
                ( flex loom                    
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ D&P  inc Nut        2.03   
                1 DEVICE PR                    
                1 PLATE PR                     
Average         1 NUT YELLOW                   
                1 THHN #14                     
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ D&P-    Mass        1.87   
                1 Device PR                    
                1 Plate PR                     
                                               
When there are a                               
lot of them and                                
most all of the                                
outlets are                                    
good like after                                
smoke damage.                                  
                                               
Device&Plate                                   
                                               
                                               
                                               
                                               


\ Dish cord           4.80   
                ( Cord connection )            
                1 Molded Cord                  
                1 romex blue                   
                2 nut yellow                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


