Decorator style comparison
Retail prices are wholesale plus tax plus 25%                   
Wholesale prices are pre tax and no labor.                      
Plates have a slightly higher install time, do we agree?        
Devices have the same install time.                             
                                                                
Deco plates no longe cost more than standard plates April 2020
Needs to be corrected of not used.                                                                 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                



Devices Retail               
                Fish-in-walls                                   0.00        0.00          
                Deco S4                                         0.55      115.80          
                Device S4                                       3.50      646.00          
.                                                               0.00        0.00          
                Deco S3                                         0.31       62.30          
                Device S3                                       0.16       35.04          
.                                                               0.00        0.00          
                Deco SW                                         0.25       50.00          
                Device SW                                       0.10       20.00          
.                                                               0.00        0.00          
                Deco PR                                         0.25       47.90          
                Device PR                                       0.10       20.00
                                                                5.22     $997.04          
                                               
Devices Wholesale            
A rip-off?      Deco S4                                         0.55      115.80          
                Device S4                                       3.50      646.00          
.                                                               0.00        0.00          
                Deco S3                                         0.31       62.30          
                Device S3                                       0.16       35.04          
.                                                               0.00        0.00          
                Deco SW                                         0.25       50.00          
                Device SW                                       0.10       20.00          
.                                                               0.00        0.00          
                Deco PR                                         0.25       47.90          
                Device PR                                       0.10       20.00
                                                                5.22     $997.04          
                                               
Plates Retail
                Fish-in-walls                                   0.00        0.00          
                Plate SW                                        0.02        4.26          
                Deco  1-Gang Elect                              0.05        9.80          
.                                                               0.00        0.00          
                Plate SW-SW                                     0.12       23.76          
                Deco  2-Gang  Elect                             0.15       28.50          
.                                                               0.00        0.00          
                Plate SW-SW-SW                                  0.12       23.96          
                Deco  3-Gang                                    0.18       35.26          
.                                                               0.00        0.00
                Deco  4-Gang                                    0.20       44.46
                                                                0.84     $170.00          
                                               
Plates w/s                   
                Deco  1-gang  Elect                             0.05        9.80          
                Plate SW                                        0.02        4.26          
.                                                               0.00        0.00          
                Deco  2-gang Elect                              0.15       28.50          
                Plate SW-SW                                     0.12       23.76          
.                                                               0.00        0.00          
                Plate SW-SW-SW                                  0.12       23.96          
                Deco  3-
.
                Deco  4-gang
                                               
                                               

