Decorator style comparison                                      
Retail prices are wholesale plus tax plus 25%                   
Wholesale prices are pre tax and no labor.                      
Plates have a slightly higher install time, do we agree?        
Devices have the same install time.                             
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Devices Retail               
                Fish-in-walls                  
                Deco S4                        
                Device S4                      
.                                              
                Deco S3                        
                Device S3                      
.                                              
                Deco SW                        
                Device SW                      
.                                              
                Deco PR                        
                Device PR                      
                                               
                                               
                                               


Devices Wholesale            
                Wholesale                      
A rip-off?      Deco S4                        
                Device S4                      
.                                              
                Deco S3                        
                Device S3                      
.                                              
                Deco SW                        
                Device SW                      
.                                              
                Deco PR                        
                Device PR                      
                                               
                                               
                                               


Plates Retail                
                Fish-in-walls                  
                Plate SW                       
                Deco  1G  Elect                
.                                              
                Plate SW-SW                    
                Deco  2G  Elect                
.                                              
                Plate SW-SW-SW                 
                Deco  3G                       
.                                              
                Deco  4G                       
                                               
                                               
                                               
                                               


Plates w/s                   
                Wholesale                      
                Deco  1G  Elect                
                Plate SW                       
.                                              
                Deco  2G  Elect                
                Plate SW-SW                    
.                                              
                Plate SW-SW-SW                 
                Deco  3G                       
.                                              
                Deco  4G                       
                                               
                                               
                                               
                                               


