Dimmer prices  and beam spreads                                 
                                                                
                                                                
 9    EZY                                                       
 14   EYF  75                                                   
 14   EXT                                                       
 24   EXZ                                                       
 40   EXN                                                       
 60   FNV                                                       
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ DIMMER-1/3                                                 AEC
                Elect                          Time    Installed
Miastro         Dimmer MALV-600                0.35     111.38  
                Dimmer MA-600                  0.35      67.85  
 remote         Dimmer MA-R                    0.30      41.81  
Touch bar       Dimmer ZP-600VA                0.25      66.40  
                Dimmer ZP-600                  0.15      29.85  
                Dimmer ZPR                     0.15      20.40  
Nob?            Dimmer S-600                   0.20      34.28  
Low voltage     Dimmer SLV-600                 0.25      60.23  
LV 3-way        Dimmer SLV-603                 0.25      72.98  
                Dimmer SELV-300                0.30      78.46  
                Dimmer SELV-303                0.30      91.22  
                                                                
                                                                
                                                                


\ DIMMER-2/3                                                    
                Dimmer Lumea-S3LV              0.25      88.67  
                Dimmer Lumea-LV                0.25      76.52  
                Dimmer Lumea-S3                0.20      49.47  
                Dimmer Lumea                   0.20      42.38  
                Dimmer Lumea-plate             0.05      10.85  
                Dimmer E-600                   0.25      50.10  
                Dimmer E-600VA                 0.25      94.75  
                Dimmer ER-3                    0.25      33.46  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ DIMMER-3/3                                                    
                Dimmer Nob-only                0.08       5.75  
Twist on/off    Dimmer Turn-on                 0.20      19.77  
Toggle dimmer   Dimmer Toggle                  0.15      16.35  
Little slider   Dimmer AYLV600                 0.30      50.25  
Slide off       Dimmer GL-600                  0.15      21.31  
Push on, turn   Dimmer Push-Push               0.15      16.35  
                Dimmer 1000W                   0.25      88.67  
                Dimmer 1500W                   0.60     172.72  
                Dimmer 2000W                   0.70     236.95  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


