Dimmer prices  and beam spreads
                                                                
                                                                
 9    EZY                                                       
 14   EYF  75                                                   
 14   EXT                                                       
 24   EXZ                                                       
 40   EXN                                         5.30         4.24             
 60   FNV                                         1.06         0.70             
                                              2,340.24                          
                                                954.00       333.56             
                                              1,386.24       693.12             
                                                  0.00         0.00             
                                                  0.00                          
                                                                
                                                                



DIMMER-1/3
                Elect                                           0.00        0.00          
Miastro         Dimmer MALV-600                                 0.35      173.00          
                Dimmer MA-600                                   0.35      115.00          
 remote         Dimmer MA-R                                     0.30       91.50          
Touch bar       Dimmer ZP-600VA                                 0.25      123.00          
                Dimmer ZP-600                                   0.25       77.00          
                Dimmer ZP                                       0.04       80.40          
Nob?            Dimmer S-600                                    0.25       79.50          
Low voltage     Dimmer SLV-600                                  0.25      113.86          
LV 3-way        Dimmer SLV-603                                  0.25      132.76          
                Dimmer SELV-300                                 0.30      145.80          
                Dimmer SELV-303                                 0.30      164.70
                                                                2.89   $1,296.52          

DIMMER-2/3
                Dimmer Lumea-S3LV                               0.25      156.00          
                Dimmer Lumea-LV                                 0.25      138.00          
                Dimmer Lumea-S3                                 0.20       93.00          
                Dimmer Lumea                                    0.20       82.50          
                Dimmer Lumea-plate                              0.05       21.00          
                Dimmer E-600                                    0.25       98.86          
                Dimmer E-600VA                                  0.25      181.00          
                Dimmer ER-3                                     0.25       74.20
                                                                1.70     $844.56          

DIMMER-3/3
                Dimmer Nob                                      0.01        3.80          
Toggle dimmer   Dimmer Toggle                                   0.15       39.00          
Little slider   Dimmer AY-600                                   0.25       71.00          
Slide off       Dimmer GL-600                                   0.15       46.36          
Push on, turn   Dimmer Push-Push                                0.15       39.00          
                \ Dimmer 1000W                                  0.00        0.00          
                \ Dimmer 1500W                                  0.00        0.00          
                \ Dmmer 2000W                                   0.00        0.00
                                                                0.71     $199.16          

Total Estimate                                                         $2,340.24                    

