Notes                                                           
CB and enclosure is less money than a safety switch.            
Should be even less as the enclosure times in NECA includes the 
time for the CB.                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Panel & CB 200A   186.44 Parts    7.00 hrs    529.44          
                1 Enclosure 200A                361.95          
                1 c-b 200a                      167.49   529.44 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Safty switch      298.41 Parts    6.00 hrs    592.41          
                1 Safety-switch 200a            550.35          
                3 FUSE 200A                      42.06   592.41 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Panel & CB 200A   118.50 Parts    7.00 hrs    118.50       AEC
                Wholesale                                       
                1 Enclosure 200A                 42.00          
                1 c-b 200a                       76.50          
                Retail                                   118.50 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Safty switch      190.46 Parts    6.00 hrs    190.46          
                Wholesale                                       
                1 Safety-switch 200a            165.50          
                3 FUSE 200A                      24.96          
                Retail                                   190.46 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Loader                                                     AEC
From \forth\prices\nps.scr                                      
need safety-switch                                              
From \forth\prices\nps.scr                                      
need enclosure                                                  
From \forth\prices\nps.scr                                      
need FUSE                                                       
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


