Notes
CB and enclosure is less money than a safety switch.            
Should be even less as the enclosure times in NECA includes the 
time for the CB.                                                
                                                                
                                                                
                                                                
                                                 16.48        13.18             
                                                  3.29         2.19             
                                              3,852.00                          
                                              2,966.40     1,037.20             
                                                885.60       442.80             
                                                  0.00         0.00             
                                                  0.00                          
                                                                
                                                                



Panel & CB 200A   186.44 Parts    7.00 hrs
                1 Enclosure 200A                                6.00    1,081.68          
                1 c-b 200a                                      1.00      333.00
                                                                7.00   $1,414.68          

Safty switch      298.41 Parts    6.00 hrs
                1 Safety-switch 200a                            1.00      333.00          
                3 FUSE 200A                                     0.24      178.32
                                                                1.24     $511.32          

Panel & CB 200A   118.50 Parts    7.00 hrs
                1 Enclosure 200A                                6.00    1,081.68          
                1 c-b 200a                                      1.00      333.00
                                                                7.00   $1,414.68          

Safty switch      190.46 Parts    6.00 hrs
                1 Safety-switch 200a                            1.00      333.00          
                3 FUSE 200A                                     0.24      178.32
                                                                1.24     $511.32          
                                                
\ Loader                                        
From \forth\prices\nps.scr                      
need safety-switch                              
From \forth\prices\nps.scr                      
need enclosure                                  
From \forth\prices\nps.scr                      
need FUSE                                       
                                                
                                                
Total Estimate                                                         $3,852.00                    

