\ Power for a 220 DRYER  Created  Nov 10, 1986       4-08-91 AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                 12.10         9.68             
                                                  2.42         1.61             
                                              2,687.95                          
                                              2,178.00       761.53             
                                                509.95       255.09             
                                                  0.00         0.00             
                                                  0.00                          
                                                                
                                                                



Open-2x4 50 Ft               
                Open-2x4                                        0.00        0.00          
The wire        50 romex 10/3                                   2.25      480.00          
The box         1 4s box                                        0.30       55.36          
Romex connector 2 romex large                                   0.26       48.76          
The plug        1 device-220 dryer                              0.20       64.00          
Plaster ring    1 4s-2g 1/2                                     0.05       12.02          
Chrome-dryer    1 4s-ind 2-1/8                                  0.20       39.66          
Circuit breaker 1 c-b 30a                                       0.30       99.16          
Cord            NIC                                             0.00        0.00          
Exaust          NIC                                             0.00        0.00
                                                                3.56     $798.96          
                                               
Neat-EMT 25-LF               
                Neat-EMT                                        0.00        0.00          
The pipe        25 EMT 1/2                                      1.12      215.60          
Couplings       3 SS-Coup 1/2                                   0.12       22.50          
Nailers         5 Strap 1/2                                     0.10       19.55          
The wire        26 3 * THHN #10                                 0.62      155.28          
The box         1 4s box                                        0.30       55.36          
The connectors  2 SS-Con 1/2                                    0.16       29.28          
The plug        1 device-220 dryer                              0.20       64.00          
THe cover       1 4s-ind 2-1/8                                  0.20       39.66          
Circuit breaker 1 C-B 30a                                       0.30       99.16          
Cord            NIC                                             0.00        0.00          
Exaust          NIC                                             0.00        0.00
                                                                3.12     $700.39          
                                               
Neat-EMT 50-LF
                Neat-EMT                                        0.00        0.00          
The pipe        50 EMT 1/2                                      2.25      433.00          
Couplings       6 SS-Coup 1/2                                   0.24       45.00          
Nailers         10 Strap  1/2                                   0.20       39.10          
The wire        165 THHN #10                                    1.32      330.00          
The box         1 4s box                                        0.30       55.36          
The connectors  2 SS-Con 1/2                                    0.16       29.28          
The plug        1 device-220 dryer                              0.20       64.00          
THe cover       1 4s-ind 2-1/8                                  0.20       39.66          
Circuit breaker 1 c-b 30a                                       0.30       99.16          
Cord        NIC 1 cord                                          0.25       54.04          
Exaust          NIC                                             0.00        0.00
                                                                5.42   $1,188.60          
                                               
Exaust outlet                                   
Hole in stucco                                                  0.00        0.00          
Outlet kit                                                      0.00        0.00          
Hose                                                            0.00        0.00          
Labor                                                           0.00        0.00          
Calking                                                         0.00        0.00          
Circ strap                                                      0.00        0.00          
                                                
                                                
Total Estimate                                                         $2,687.95                    

