\ Power for a 220 DRYER  Created  Nov 10, 1986       4-08-91 AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Open-2x4 50 Ft               
                Open-2x4                       
The wire        50 romex 10/3                  
The box         1 4s box                       
Romex connector 2 romex large                  
The plug        1 device-220 dryer             
Plaster ring    1 4s-2g 1/2                    
Chrome-dryer    1 4s-ind 2-1/8                 
Circuit breaker 1 c-b 30a                      
Cord            NIC                            
Exaust          NIC                            
                                               
                                               
                                               
                                               
                                               


Neat-EMT 25-LF               
                Neat-EMT                       
The pipe        25 EMT 1/2                     
Couplings       3 SS-Coup 1/2                  
Nailers         5 Strap 1/2                    
The wire        26 3 * THHN #10                
The box         1 4s box                       
The connectors  2 SS-Con 1/2                   
The plug        1 device-220 dryer             
THe cover       1 4s-ind 2-1/8                 
Circuit breaker 1 C-B 30a                      
Cord            NIC                            
Exaust          NIC                            
                                               
                                               
                                               


Neat-EMT 50-LF               
                Neat-EMT                       
The pipe        50 EMT 1/2                     
Couplings       6 SS-Coup 1/2                  
Nailers         10 Strap  1/2                  
The wire        165 THHN #10                   
The box         1 4s box                       
The connectors  2 SS-Con 1/2                   
The plug        1 device-220 dryer             
THe cover       1 4s-ind 2-1/8                 
Circuit breaker 1 c-b 30a                      
Cord            NIC                            
Exaust          NIC                            
                                               
                                               
                                               


Exaust outlet                                                   
Hole in stucco                                                  
Outlet kit                                                      
Hose                                                            
Labor                                                           
Calking                                                         
Circ strap                                                      
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


