Electro Metalic Tubing
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LF-EMT        Out of date need be wholesale       89-07-12 AEC
and hours have to be in whole numbers per hund                  
:   15A 1/2 2-14         63.50 Parts    5.75 hrs    345.25      
:   15A 1/2 3-14         76.34 Parts    6.36 hrs    387.98      
:   20A 1/2 2-12         76.34 Parts    6.06 hrs    373.28      
:   20A 1/2 3-12         88.34 Parts    6.66 hrs    414.68      
:   30A 1/2 3-10        136.34 Parts    7.26 hrs    492.08      
:   50A 3/4 3-8         213.09 Parts    8.86 hrs    647.23      
:   65A 3/4 3-6         245.29 Parts    9.36 hrs    703.93      
:   85A 1-in #4         370.11 Parts   11.46 hrs    931.65      
:   85A 1-1/4 #4        412.15 Parts   12.96 hrs  1,047.19      
:   115A 1-in #2        529.11 Parts   12.66 hrs  1,149.45      
:   130A 1-1/4 #1       688.15 Parts   14.76 hrs  1,411.39      
:   150A 1-1/4 1/0      799.15 Parts   15.36 hrs  1,551.79      
:   200A 1-1/2 3/0    1,091.86 Parts   17.06 hrs  1,927.80      
                                                                

Box only 4S No EMT           
                 1 4S BOX                      
                 1 4S-IND pr                   
                 2 SS-CON 1/2                  
                 2 NUT RED                     
                 1 DEVICE pr                   
                                               
                                               
(J) only 4S No EMT           
                 1 4S BOX                      
                 1 4S BL                       
                 2 SS-CON 1/2                  
                 2 NUT RED                     
                                               
                                               
Handy box only        7.60 Parts    0.80 hrs     46.80          
                 1 Handy box                     16.67          
                 1 Handy pr-cover                 6.78          
                 2 SS-CON 1/2                     8.64          
                 2 NUT RED                        6.08          
                 1 DEVICE pr                      6.37          
                 1 permit outlet                  1.16    46.80 
                                                                
                                                                
PL-ve  ( No bends ) 82.50    
                ( Straight runs in EMT         
                ( 12 feet between outlets      
                ( About the same as a PL-Easy  
12' for cost of  3   EMT      1/2              
9' mtls only     2 dollars parts               
Wire            25   THHN     #12              
Connectors       2   ss-con   1/2              
Couplings        3   ss-coup  1/2              
Nail straps      4   strap   1/2               
Wire nuts        2   nut      red              
Four square box  1   4S   BOX                  
Plaster ring     1   4S-LT    5/8              
                                               
                                               
PL-e ( 10' emt)  82.50       
                10   EMT      1/2              
                22   THHN     #12              
                 1   4S   BOX                  
                 2   ss-con   1/2              
                 3   ss-coup  1/2              
                 4   strap    1/2              
                 2   nut      red              
                 1   device   pr               
                 1   4S-ind   pr               
                                               
                                               
PL-m ( 15' emt)  82.50       
                15   EMT      1/2              
                32   THHN     #12              
                 1   4S   BOX                  
                 2   ss-con   1/2              
                 3   ss-coup  1/2              
                 4   strap    1/2              
                 2   nut      red              
                 1   device   pr               
                 1   4S-ind   pr               
                                               
                                               
PL   ( 20' emt)              
                35.00 per-hour                 
Raceway         20   EMT      1/2              
Wire            45   THHN     #12              
Connectors       2   SS-Con   1/2              
Couplings        3   SS-Coup  1/2              
Nail straps      4   Strap    1/2              
Wire nuts        2   Nut      red              
Four square box  1   4S       BOX              
Indust cover     1   4S-Ind   pr               
Easy gr. plug    1   Device   pr               
                                               
get ss-con      ( Typical plug outlet )        
get ss-coup     ( 20 feet may be too long )    
get strap       ( but we don't want to be )    
                ( too short )                  


Spare                                                           
                                                                
                                                                
S3   ( 17' emt )   82.50     
Raceway         17   EMT      1/2              
Wire            18  3 *  THHN #12              
Connectors       2   ss-con   1/2              
Couplings        3   ss-coup  1/2              
Nail straps      4   strap   1/2               
Wire nuts        2   nut      red              
Four square box  1   4S   BOX                  
Plaster ring     1   4S-LT    5/8              
Device           1   device S3                 
                                               
                                               
S4   ( 17' emt )             
Raceway         17   EMT      1/2              
Wire            18  3 *  THHN #12              
Connectors       2   ss-con   1/2              
Couplings        3   ss-coup  1/2              
Nail straps      4   strap   1/2               
Wire nuts        2   nut      red              
Four square box  1   4S   BOX                  
Plaster ring     1   4S-LT    5/8              
Device           1   device S4                 
                                               
                                               
LT   ( 20' emt )             
                ( Typical outlet in EMT        
                ( 20 feet is sometimes a bit   
                ( long, but don't want to be   
                ( too short either.            
Raceway         20   EMT      1/2              
Wire            45   THHN     #12              
Connectors       2   SS-Con   1/2              
Couplings        3   SS-Coup  1/2              
Nail straps      4   strap   1/2               
Wire nuts        2   nut      red              
Four square box  1   4S   BOX                  
Plaster ring     1   4S-LT    5/8              
                                               
                                               
LT Out door lite             
7.06                 1   RT-BOX   4-oct        
                    18   EMT      1/2          
                     2   rt-con   1/2          
                     3   rt-coup  1/2          
                     4   strap   1/2           
                  20 2 * THHN     #12          
                     2   nut      red          
Fixture not NIC                                
                                               
                                               
PR Out door plug             
                 1   RT-BOX   4-oct            
                 18   EMT      1/2             
                 2   rt-con   1/2              
                 3   rt-coup  1/2              
                 4   strap   1/2               
                 20 2 * THHN     #12           
                 2   nut      red              
                 1   device   pr               
                 1   RT-Plate GFI              
                                               
                                               
(J) ( Rx to emt              
                1 4S BOX                       
                1 4S BLANK                     
                1 SS-CON 1/2                   
                2 ROMEX BLUE                   
                                               
                                               
15A ( 1/2 2-14 )             
                50.00 per-hour                 
                100 emt 1/2                    
                200 THHN #14                   
                25 strap 1/2                   
                                               
                                               
15A ( 1/2 3-14 )             
                   100 emt     1/2             
                   300 THHN    #14             
                    25 strap  1/2              
                    11 SS-COUP 1/2             
                                               
                                               
20A ( 1/2 2-12 )  82.50 hr   
                100 emt     1/2                
                200 THHN    #12                
                 25 strap   1/2                
                 11 SS-COUP 1/2                
                                               
                                               
20A ( 1/2 3-12 )             
                100 emt     1/2                
                300 THHN    #12                
                25  strap   1/2                
                11  SS-COUP 1/2                
                                               
                                               
30A ( 1/2 3-10 )             
                100 EMT     1/2                
                300 THHN    #10                
                11  SS-COUP 1/2                
                25  strap  1/2                 
                                               
                                               
30A ( 3/4 9-#10 NINE )       
                100 EMT     3/4                
                900 THHN    #10                
                11  SS-COUP 3/4                
                25  strap  3/4                 
                                               
                                               
50A ( 3/4 3-8 )              
                50.00 PER-HOUR                 
                100 EMT     3/4                
                300 THHN    #8                 
                11  SS-COUP 3/4                
                25  strap  3/4                 
                                               
                                               
65A ( 3/4 3-6 )              
                100 EMT     3/4                
                300 THHN    #6                 
                11  SS-COUP 3/4                
                15  STRAP   3/4                
                                               
                                               
85A ( 1-in #4 )              
                100 EMT     1-IN               
                300 THHN    #4                 
                11  SS-COUP 1-IN               
                15  STRAP   1-IN               
                                               
                                               
85A ( 1-1/4 #4 )             
                100 EMT     1-1/4              
                300 THHN    #4                 
                11  SS-COUP 1-1/4              
                15  STRAP   1-1/4              
                                               
                                               
115A ( 1-in #2 )             
                100 EMT     1-IN               
                300 THHN    #2                 
                11  SS-COUP 1-IN               
                15  STRAP   1-IN               
                                               
                                               
130A ( 1-1/4 #1)             
                100 EMT     1-1/4              
                300 THHN    #1                 
                11  SS-COUP 1-1/4              
                15  STRAP   1-1/4              
                                               
                                               
150A 1-1/4 1/0 )             
                100 EMT     1-1/4              
                300 THHN    1/0                
                11  SS-COUP 1-1/4              
                15  STRAP   1-1/4              
                                               
                                               
200A 1-1/2 3/0 )             
                100 EMT 1-1/2                  
                300 THHN 3/0                  1
                11  SS-COUP 1-1/2              
                15  STRAP 1-1/2                
                                               
                                               
225A 1-1/2 3/0 )             
                100 EMT 1-1/2                  
                300 THHN 3/0                  1
                11  SS-COUP 1-1/2              
                15  STRAP 1-1/2                
                                               
                                               
300A 2-in 300mcm           1,
                100 EMT 2-in                   
                300 THHN 300mcm               1
                11  SS-COUP 2-in               
                15  STRAP 2-in                 
                                               
                                               
380A ( 3-in 500mc                  25.56 hrs  3,389.78          
                100 EMT 3-in                    910.00          
                300 THHN 500xxx               2,280.00          
                11  SS-COUP 3-in                152.68          
                15  STRAP 3-in                   47.10 3,389.78 
                                                                
                                                                
X-ray ( 1-in #2 )            
                100 EMT     1-IN               
                200 THHN    #2                 
                100 thhn    #8                 
                11  SS-COUP 1-IN               
                15  STRAP   1-IN               
                                               
                                               
Quad at same time            
                55.00 per-hour                 
                1 device pr                    
                2 nut red                      
                2 thhn #12                     
total                                          
                                               
                                               
Quad conversion              
                                               
4S and SW-Box                                  
are same cost.                                 
Ring is needed  1 4s-2g 5/8                    
                1 device pr                    
                2 nut red                      
                2 thhn #12                     
                                               
                                               
15A 1/2RT 3.0 14             
                100 emt     1/2                
                300 THHN    #14                
                 25 strap  1/2                 
                 11 RT-COUP 1/2                
                                               
                                               
20A 1/2RT 3.0 12             
                100 emt     1/2                
                300 THHN    #12                
                 25 strap  1/2                 
                 11 RT-COUP 1/2                
                                               
                                               
Empty 1/2 R.T.               
                100 emt 1/2                    
                0 THHN #12                     
                25 strap 1/2                   
                11 RT-COUP 1/2                 
                1 rt-box 3-hub                 
                1 plate-rt bl                  
                                               
                                               
Empty 50% R.T.               
                0 THHN #12                     
                100 emt 1/2                    
                25 strap 1/2                   
                6 RT-COUP 1/2                  
                5 RT-COUP 1/2                  
                1 4s box                       
                1 4s bl                        
                1 rt-90 1/2                    
                1 ss-con 1/2                   
                                               
                                               
Empty 1/2                    
                100 emt 1/2                    
                0 THHN #12                     
                25 STRAP 1/2                   
                11 SS-COUP 1/2                 
                0 4s box                       
                0 4s bl                        
                2 ss-con 1/2                   
                0 ss-90 1/2                    
                                               
                                               
Empty 3/4                    
                100 emt 3/4                    
                0 THHN #12                     
                25 Strap 3/4                   
                11 SS-Coup 3/4                 
                0 5s box                       
                0 5s bl                        
                2 ss-con 3/4                   
                0 ss-90 3/4                    
                                               
                                               
Empty 1-in                   
                100 emt 1-in                   
                0 THHN #12                     
                25 Strap 1-in                  
                11 SS-Coup 1-in                
                0 5s box                       
                0 5s bl                        
                2 ss-con 1-in                  
                                               
                                               
Empty 1-1/4                  
                100 emt 1-1/4                  
                0 THHN #12                     
                25 Strap 1-1/4                 
                11 SS-Coup 1-1/4               
                0 5s box                       
                0 5s bl                        
                2 ss-con 1-1/4                 
                                               
                                               
Empty 1-1/2                  
                100 emt 1-1/2                  
                0 THHN #12                     
                25 Strap 1-1/2                 
                11 SS-Coup 1-1/2               
                0 5s box                       
                0 5s bl                        
                2 ss-con 1-1/2                 
                                               
                                               
Empty 2-in                   
                100 emt 2-in                   
                0 THHN #12                     
                25 Strap 2-in                  
                11 SS-Coup 2-in                
                0 5s box                       
                0 5s bl                        
                2 ss-con 2-in                  
                                               
                                               
1 Hole VS 2 Hole                    0.08 hrs      5.92          
                1 strap 2-in                      2.09          
                1 secure toggle                                 
1 washer                                                   5.92 
                                                                
                                                                
1 Hole VS 2 Hole                    0.14 hrs      8.56          
                1 strap-2-grs 2-in                0.76          
                2 secure toggle                   7.80          
1 washer                                                   8.56 
                                                                
                                                                
Circ study 1/2               
                50 lf-emt 1/2                  
                100 thhn #12                   
                                               
                                               
Circ study 20a               
                50 lf-emt 20a                  
                                               
                                               
PVC vs EMT study             
                1 4s vb                        
                1 4s-1g 5/8                    
                                               
                                               
PVC vs EMT study             rts    0.30 hrs      0.51          
                Wholesale                                       
                1 pvc 1g                          0.51     0.51 
                                                                
                                                                
2.76                                                            
 .51                                                            
 ---                                                            
1.21 x 20 = 24.20   This is more than the loss of the dimmers   
                                                                
                                                                
PL-220                       ax    0.75 hrs      54.01          
                1 4S BOX                         16.89          
                1 4S-IND 1-9/16                  12.47          
                1 DEVICE PL-220                  24.65    54.01 
                                                                
                                                                
S3   ( 35' emt )             
Raceway         35   EMT      1/2              
Wire            37  3 *  THHN #14              
Connectors       2   ss-con   1/2              
Couplings        4   ss-coup  1/2              
Nail straps      8   strap   1/2               
Wire nuts        2   nut      red              
Four square box  1   4S   BOX                  
                 1   4S   EXT                  
Cover Plate      2   4S-IND  SW                
Device           2   device S3                 
                                               
                                               
65A-3P ( 3/4 4-6 )           
                100 EMT     3/4                
                400 THHN    #6                 
                11  SS-COUP 3/4                
                15  STRAP   3/4                
                                               
                                               
Range 50 LF-emt              
                1 C-B 50A                      
1/2 Will Fit    50 LF-EMT 3/4                  
                2 ss-con 3/4                   
                1 4s box                       
                50 3 * THHN #8                 
                1 Device-220 Dryer             
                1 4s-ind 2-1/8                 
                                               
                                               
Dryer 50 LF-emt              
Circuit breaker 1 C-B 30A                      
The raceway     50 LF-EMT 1/2                  
The connectors  2 ss-con 1/2                   
The box         1 4s box                       
The wire        50 3 * THHN #10                
The plug        1 Device-220 Dryer             
Cover           1 4s-ind 2-1/8                 
                                               
                                               
PR EMT is 66%                
Raceway         20   EMT      1/2              
Connectors       2   ss-con   1/2              
Couplings        3   ss-coup  1/2              
Nail straps      4   strap    1/2              
Four square box  1   4S       BOX              
                                               
                                               
PR Wire is 33%               
Wire            45   THHN     #12              
Wire nuts        2   nut      red              
Indust cover     1   4S-ind   pr               
Easy gr. plug    1   device   pr               
                                               
                                               

