Electro Metalic Tubing
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                330.32       264.25             
                                                 66.06        44.04             
                                             37,940.52                          
                                             16,903.65     5,910.36             
                                             21,036.87    10,528.63             
                                                  0.00         0.00             
                                                  0.00                          
                                                                
                                                                



\s
\ LF-EMT        Out of date need be wholesale
and hours have to be in whole numbers per hund
:   15A 1/2 2-14         63.50 Parts    5.75 hrs
:   15A 1/2 3-14         76.34 Parts    6.36 hrs
:   20A 1/2 2-12         76.34 Parts    6.06 hrs
:   20A 1/2 3-12         88.34 Parts    6.66 hrs
:   30A 1/2 3-10        136.34 Parts    7.26 hrs
:   50A 3/4 3-8         213.09 Parts    8.86 hrs
:   65A 3/4 3-6         245.29 Parts    9.36 hrs
:   85A 1-in #4         370.11 Parts   11.46 hrs
:   85A 1-1/4 #4        412.15 Parts   12.96 hrs
:   115A 1-in #2        529.11 Parts   12.66 hrs
:   130A 1-1/4 #1       688.15 Parts   14.76 hrs
:   150A 1-1/4 1/0      799.15 Parts   15.36 hrs
:   200A 1-1/2 3/0    1,091.86 Parts   17.06 hrs
\s


                elect


Box only 4S No EMT
                 1 4S BOX                              1.36     0.30       40.96
                 1 4S-IND pr                           3.58     0.20       29.98
                 2 SS-CON 1/2                          0.48     0.16       21.60
                 2 NUT RED                             0.22     0.12       16.06
                 1 DEVICE pr                           2.00     0.10       15.20
                                                      $7.64     0.88     $123.80

(J) only 4S No EMT
                 1 4S BOX                              1.36     0.30       40.96
                 1 4S BL                               1.34     0.16       22.46
                 2 SS-CON 1/2                          0.48     0.16       21.60
                 2 NUT RED                             0.22     0.12       16.06
                                                      $3.40     0.74     $101.08

Handy box only        7.60 Parts    0.80 hrs
                 1 Handy box                           4.30     0.30       43.90
                 1 Handy-cover PR                      2.23     0.07       11.47
                 2 SS-CON 1/2                          0.48     0.16       21.60
                 2 NUT RED                             0.22     0.12       16.06
                 1 DEVICE pr                           2.00     0.10       15.20
                 1 permit 20-outlets-2               490.00     0.00      490.00
                                                    $499.23     0.75     $598.23

PL-ve  ( No bends ) 82.50
                ( Straight runs in EMT                 0.00     0.00        0.00
                ( 12 feet between outlets              0.00     0.00        0.00
                ( About the same as a PL-Easy          0.00     0.00        0.00
12' for cost of  3   EMT      1/2                      1.68     0.13       18.84
9' mtls only     2 dollars parts                       4.00     0.00        4.00
Wire            25   THHN     #12                      9.50     0.15       29.30
Connectors       2   ss-con   1/2                      0.48     0.16       21.60
Couplings        3   ss-coup  1/2                      0.90     0.12       16.74
Nail straps      4   strap   1/2                       1.24     0.08       11.80
Wire nuts        2   nut      red                      0.22     0.12       16.06
Four square box  1   4S   BOX                          1.36     0.30       40.96
Plaster ring     1   4S-LT    5/8                      1.81     0.15       21.61
                                                     $21.19     1.21     $180.91

PL-e ( 10' emt)  82.50
                10   EMT      1/2                      5.60     0.45       65.00
                22   THHN     #12                      8.36     0.13       25.52
                 1   4S   BOX                          1.36     0.30       40.96
                 2   ss-con   1/2                      0.48     0.16       21.60
                 3   ss-coup  1/2                      0.90     0.12       16.74
                 4   strap    1/2                      1.24     0.08       11.80
                 2   nut      red                      0.22     0.12       16.06
                 1   device   pr                       2.00     0.10       15.20
                 1   4S-ind   pr                       3.58     0.20       29.98
                                                     $23.74     1.66     $242.86

PL-m ( 15' emt)  82.50
                15   EMT      1/2                      8.40     0.67       96.84
                32   THHN     #12                     12.16     0.19       37.24
                 1   4S   BOX                          1.36     0.30       40.96
                 2   ss-con   1/2                      0.48     0.16       21.60
                 3   ss-coup  1/2                      0.90     0.12       16.74
                 4   strap    1/2                      1.24     0.08       11.80
                 2   nut      red                      0.22     0.12       16.06
                 1   device   pr                       2.00     0.10       15.20
                 1   4S-ind   pr                       3.58     0.20       29.98
                                                     $30.34     1.94     $286.42

PL   ( 20' emt)
                132.00 per-hour                        0.00     0.00        0.00
Raceway         20   EMT      1/2                     11.20     0.90      130.00
Wire            45   THHN     #12                     17.10     0.27       52.74
Connectors       2   SS-Con   1/2                      0.48     0.16       21.60
Couplings        3   SS-Coup  1/2                      0.90     0.12       16.74
Nail straps      4   Strap    1/2                      1.24     0.08       11.80
Wire nuts        2   Nut      red                      0.22     0.12       16.06
Four square box  1   4S       BOX                      1.36     0.30       40.96
Indust cover     1   4S-Ind   pr                       3.58     0.20       29.98
Easy gr. plug    1   Device   pr                       2.00     0.10       15.20
                                                     $38.08     2.25     $335.08

get ss-con      ( Typical plug outlet )
get ss-coup     ( 20 feet may be too long )            0.00     0.00        0.00
get strap       ( but we don't want to be )            0.00     0.00        0.00
                ( too short )                          0.00     0.00        0.00


Spare


S3   ( 17' emt )   82.50
Raceway         17   EMT      1/2                      9.52     0.76      109.84
Wire            18  3 *  THHN #12                     20.52     0.32       62.76
Connectors       2   ss-con   1/2                      0.48     0.16       21.60
Couplings        3   ss-coup  1/2                      0.90     0.12       16.74
Nail straps      4   strap   1/2                       1.24     0.08       11.80
Wire nuts        2   nut      red                      0.22     0.12       16.06
Four square box  1   4S   BOX                          1.36     0.30       40.96
Plaster ring     1   4S-LT    5/8                      1.81     0.15       21.61
Device           1   device S3                         6.24     0.16       27.36
                                                     $42.29     2.17     $328.73

S4   ( 17' emt )
Raceway         17   EMT      1/2                      9.52     0.76      109.84
Wire            18  3 *  THHN #12                     20.52     0.32       62.76
Connectors       2   ss-con   1/2                      0.48     0.16       21.60
Couplings        3   ss-coup  1/2                      0.90     0.12       16.74
Nail straps      4   strap   1/2                       1.24     0.08       11.80
Wire nuts        2   nut      red                      0.22     0.12       16.06
Four square box  1   4S   BOX                          1.36     0.30       40.96
Plaster ring     1   4S-LT    5/8                      1.81     0.15       21.61
Device           1   device S4-110                    19.56     0.30       59.16
                                                     $55.61     2.31     $360.53

LT   ( 20' emt )
                ( Typical outlet in EMT                0.00     0.00        0.00
                ( 20 feet is sometimes a bit           0.00     0.00        0.00
                ( long, but don't want to be           0.00     0.00        0.00
                ( too short either.                    0.00     0.00        0.00
Raceway         20   EMT      1/2                     11.20     0.90      130.00
Wire            45   THHN     #12                     17.10     0.27       52.74
Connectors       2   SS-Con   1/2                      0.48     0.16       21.60
Couplings        3   SS-Coup  1/2                      0.90     0.12       16.74
Nail straps      4   strap   1/2                       1.24     0.08       11.80
Wire nuts        2   nut      red                      0.22     0.12       16.06
Four square box  1   4S   BOX                          1.36     0.30       40.96
Plaster ring     1   4S-LT    5/8                      1.81     0.15       21.61
                                                     $34.31     2.10     $311.51

LT Out door lite
7.06                ( 1 ) RT-BOX   4-oct               0.00     0.00        0.00
                    18   EMT      1/2                 10.08     0.81      117.00
                     2   rt-con   1/2                  3.18     0.24       34.86
                     3   rt-coup  1/2                  4.32     0.18       28.08
                     4   strap   1/2                   1.24     0.08       11.80
                  20 2 * THHN     #12                 15.20     0.24       46.88
                     2   nut      red                  0.22     0.12       16.06
                                                     $34.24     1.67     $254.68

PR Out door plug
                ( 1 )  RT-BOX   4-oct                  0.00     0.00        0.00
                 18   EMT      1/2                    10.08     0.81      117.00
                 2   rt-con   1/2                      3.18     0.24       34.86
                 3   rt-coup  1/2                      4.32     0.18       28.08
                 4   strap   1/2                       1.24     0.08       11.80
                 20 2 * THHN     #12                  15.20     0.24       46.88
                 2   nut      red                      0.22     0.12       16.06
                 1   device   pr                       2.00     0.10       15.20
                 1   RT-Plate GFI                     10.00     0.15       29.80
                                                     $46.24     1.92     $299.68

(J) ( Rx to emt
                1 4S BOX                               1.36     0.30       40.96
                ( 1 4S BLANK )                         0.00     0.00        0.00
                1 SS-CON 1/2                           0.24     0.08       10.80
                2 ROMEX BLUE                           1.04     0.22       30.08
                                                      $2.64     0.60      $81.84

15A ( 1/2 2-14 )
                50.00 per-hour                         0.00     0.00        0.00
                100 emt 1/2                           56.00     4.50      281.00
                200 THHN #14                          56.00     1.00      106.00
                25 strap 1/2                           7.75     0.50       32.75
                                                    $119.75     6.00     $419.75

15A ( 1/2 3-14 )
                   100 emt     1/2                    56.00     4.50      281.00
                   300 THHN    #14                    84.00     1.50      159.00
                    25 strap  1/2                      7.75     0.50       32.75
                    11 SS-COUP 1/2                     3.30     0.44       25.30
                                                    $151.05     6.94     $498.05

20A ( 1/2 2-12 )  82.50 hr
                100 emt     1/2                       56.00     4.50      281.00
                200 THHN    #12                       76.00     1.20      136.00
                 25 strap   1/2                        7.75     0.50       32.75
                 11 SS-COUP 1/2                        3.30     0.44       25.30
                                                    $143.05     6.64     $475.05

20A ( 1/2 3-12 )
                100 emt     1/2                       56.00     4.50      281.00
                300 THHN    #12                      114.00     1.80      204.00
                25  strap   1/2                        7.75     0.50       32.75
                11  SS-COUP 1/2                        3.30     0.44       25.30
                                                    $181.05     7.24     $543.05

30A ( 1/2 3-10 )
                100 EMT     1/2                       56.00     4.50      281.00
                300 THHN    #10                      168.00     2.40      288.00
                11  SS-COUP 1/2                        3.30     0.44       25.30
                25  strap  1/2                         7.75     0.50       32.75
                                                    $235.05     7.84     $627.05

30A ( 3/4 9-#10 NINE )
                100 EMT     3/4                      100.00     5.00      350.00
                900 THHN    #10                      504.00     7.20      864.00
                11  SS-COUP 3/4                        8.14     0.55       35.64
                25  strap  3/4                         9.50     0.25       22.00
                                                    $621.64    13.00   $1,271.64

50A ( 3/4 3-8 )
                50.00 PER-HOUR                         0.00     0.00        0.00
                100 EMT     3/4                      100.00     5.00      350.00
                300 THHN    #8                       216.00     3.00      366.00
                11  SS-COUP 3/4                        8.14     0.55       35.64
                25  strap  3/4                         9.50     0.25       22.00
                                                    $333.64     8.80     $773.64

65A ( 3/4 3-6 )
                100 EMT     3/4                      100.00     5.00      350.00
                300 THHN    #6                       318.00     3.60      498.00
                11  SS-COUP 3/4                        8.14     0.55       35.64
                15  STRAP   3/4                        5.70     0.15       13.20
                                                    $431.84     9.30     $896.84

85A ( 1-in #4 )
                100 EMT     1-IN                     168.00     5.50      443.00
                300 THHN    #4                       609.00     4.20      819.00
                11  SS-COUP 1-IN                      14.30     0.66       47.30
                15  STRAP   1-IN                       3.00     0.15       10.50
                                                    $794.30    10.51   $1,319.80

85A ( 1-1/4 #4 )
                100 EMT     1-1/4                    278.00     6.20      588.00
                300 THHN    #4                       609.00     4.20      819.00
                11  SS-COUP 1-1/4                     24.75     0.77       63.25
                15  STRAP   1-1/4                     10.20     0.15       17.70
                                                    $921.95    11.32   $1,487.95

115A ( 1-in #2 )
                100 EMT     1-IN                     168.00     5.50      443.00
                300 THHN    #2                       882.00     5.40    1,152.00
                11  SS-COUP 1-IN                      14.30     0.66       47.30
                15  STRAP   1-IN                       3.00     0.15       10.50
                                                  $1,067.30    11.71   $1,652.80

130A ( 1-1/4 #1)
                100 EMT     1-1/4                    278.00     6.20      588.00
                300 THHN    #1                     1,164.00     6.00    1,464.00
                11  SS-COUP 1-1/4                     24.75     0.77       63.25
                15  STRAP   1-1/4                     10.20     0.15       17.70
                                                  $1,476.95    13.12   $2,132.95

150A 1-1/4 1/0 )
                100 EMT     1-1/4                    278.00     6.20      588.00
                300 THHN    1/0                      768.00     6.60    1,098.00
                11  SS-COUP 1-1/4                     24.75     0.77       63.25
                15  STRAP   1-1/4                     10.20     0.15       17.70
                                                  $1,080.95    13.72   $1,766.95

200A 1-1/2 3/0 )
                100 EMT 1-1/2                        331.00     7.00      681.00
                300 THHN 3/0                       2,088.00     7.80    2,478.00
                11  SS-COUP 1-1/2                     35.97     0.88       79.97
                15  STRAP 1-1/2                       18.45     0.15       25.95
                                                  $2,473.42    15.83   $3,264.92

225A 1-1/2 3/0 )
                100 EMT 1-1/2                        331.00     7.00      681.00
                300 THHN 3/0                       2,088.00     7.80    2,478.00
                11  SS-COUP 1-1/2                     35.97     0.88       79.97
                15  STRAP 1-1/2                       18.45     0.15       25.95
                                                  $2,473.42    15.83   $3,264.92

300A 2-in 300mcm           1,
                100 EMT 2-in                         389.00     8.00      789.00
                300 THHN 300mcm                    1,872.00    10.50    2,397.00
                11  SS-COUP 2-in                      47.85     0.99       97.35
                15  STRAP 2-in                        35.40     0.15       42.90
                                                  $2,344.25    19.64   $3,326.25

380A ( 3-in 500mc                  25.56 hrs  3,
                100 EMT 3-in                         926.00    11.00    1,476.00
                ( 300 THHN 500xxx  )                   0.00     0.00        0.00
                11  SS-COUP 3-in                     136.62     1.21      197.12
                15  STRAP 3-in                        58.80     0.15       66.30
                                                  $1,121.42    12.36   $1,739.42

X-ray ( 1-in #2 )
                100 EMT     1-IN                     168.00     5.50      443.00
                200 THHN    #2                       588.00     3.60      768.00
                100 thhn    #8                        72.00     1.00      122.00
                11  SS-COUP 1-IN                      14.30     0.66       47.30
                15  STRAP   1-IN                       3.00     0.15       10.50
                                                    $845.30    10.91   $1,390.80

Quad at same time
                55.00 per-hour                         0.00     0.00        0.00
                1 device pr                            2.00     0.10        7.50
                2 nut red                              0.22     0.12        6.82
                2 thhn #12                             0.76     0.01        1.31
total                                                  0.00     0.00        0.00
                                                      $2.98     0.23      $15.63

Quad conversion


4S and SW-Box
are same cost.                                         0.00     0.00        0.00
Ring is needed  1 4s-2g 5/8                            2.32     0.15       10.57
                1 device pr                            2.00     0.10        7.50
                2 nut red                              0.22     0.12        6.82
                2 thhn #12                             0.76     0.01        1.31
                                                      $5.30     0.38      $26.20

15A 1/2RT 3.0 14
                100 emt     1/2                       56.00     4.50      303.50
                300 THHN    #14                       84.00     1.50      166.50
                 25 strap  1/2                         7.75     0.50       35.25
                 11 RT-COUP 1/2                       15.84     0.66       52.14
                                                    $163.59     7.16     $557.39

20A 1/2RT 3.0 12
                100 emt     1/2                       56.00     4.50      303.50
                300 THHN    #12                      114.00     1.80      213.00
                 25 strap  1/2                         7.75     0.50       35.25
                 11 RT-COUP 1/2                       15.84     0.66       52.14
                                                    $193.59     7.46     $603.89

Empty 1/2 R.T.
                100 emt 1/2                           56.00     4.50      303.50
                0 THHN #12                             0.00     0.00        0.00
                25 strap 1/2                           7.75     0.50       35.25
                11 RT-COUP 1/2                        15.84     0.66       52.14
                1 rt-box 3-hub                         6.74     0.80       50.74
                ( 1 plate-rt bl )                      0.00     0.00        0.00
                                                     $86.33     6.46     $441.63

Empty 50% R.T.
                0 THHN #12                             0.00     0.00        0.00
                100 emt 1/2                           56.00     4.50      303.50
                25 strap 1/2                           7.75     0.50       35.25
                6 RT-COUP 1/2                          8.64     0.36       28.44
                5 RT-COUP 1/2                          7.20     0.30       23.70
                1 4s box                               1.36     0.30       17.86
                1 4s bl                                1.34     0.16       10.14
                1 rt-90 1/2                            3.42     0.60       36.42
                1 ss-con 1/2                           0.24     0.08        4.64
                                                     $85.95     6.80     $459.95

Empty 1/2
                100 emt 1/2                           56.00     4.50      303.50
                0 THHN #12                             0.00     0.00        0.00
                25 STRAP 1/2                           7.75     0.50       35.25
                11 SS-COUP 1/2                         3.30     0.44       27.50
                0 4s box                               0.00     0.00        0.00
                0 4s bl                                0.00     0.00        0.00
                2 ss-con 1/2                           0.48     0.16        9.28
                0 ss-90 1/2                            0.00     0.00        0.00
                                                     $67.53     5.60     $375.53

Empty 3/4
                100 emt 3/4                          100.00     5.00      375.00
                0 THHN #12                             0.00     0.00        0.00
                25 Strap 3/4                           9.50     0.25       23.25
                11 SS-Coup 3/4                         8.14     0.55       38.39
                0 5s box                               0.00     0.00        0.00
                0 5s bl                                0.00     0.00        0.00
                2 ss-con 3/4                           0.84     0.20       11.84
                0 ss-90 3/4                            0.00     0.00        0.00
                                                    $118.48     6.00     $448.48

Empty 1-in
                100 emt 1-in                         168.00     5.50      470.50
                0 THHN #12                             0.00     0.00        0.00
                25 Strap 1-in                          5.00     0.25       18.75
                11 SS-Coup 1-in                       14.30     0.66       50.60
                0 5s box                               0.00     0.00        0.00
                0 5s bl                                0.00     0.00        0.00
                2 ss-con 1-in                          1.56     0.24       14.76
                                                    $188.86     6.65     $554.61

Empty 1-1/4
                100 emt 1-1/4                        278.00     6.20      619.00
                0 THHN #12                             0.00     0.00        0.00
                25 Strap 1-1/4                        17.00     0.25       30.75
                11 SS-Coup 1-1/4                      24.75     0.77       67.10
                0 5s box                               0.00     0.00        0.00
                0 5s bl                                0.00     0.00        0.00
                2 ss-con 1-1/4                         4.00     0.32       21.60
                                                    $323.75     7.54     $738.45

Empty 1-1/2
                100 emt 1-1/2                        331.00     7.00      716.00
                0 THHN #12                             0.00     0.00        0.00
                25 Strap 1-1/2                        30.75     0.25       44.50
                11 SS-Coup 1-1/2                      35.97     0.88       84.37
                0 5s box                               0.00     0.00        0.00
                0 5s bl                                0.00     0.00        0.00
                2 ss-con 1-1/2                         6.02     0.40       28.02
                                                    $403.74     8.53     $872.89

Empty 2-in
                100 emt 2-in                         389.00     8.00      829.00
                0 THHN #12                             0.00     0.00        0.00
                25 Strap 2-in                         59.00     0.25       72.75
                11 SS-Coup 2-in                       47.85     0.99      102.30
                0 5s box                               0.00     0.00        0.00
                0 5s bl                                0.00     0.00        0.00
                2 ss-con 2-in                          8.10     0.50       35.60
                                                    $503.95     9.74   $1,039.65

1 Hole VS 2 Hole                    0.08 hrs
                1 strap 2-in                           2.36     0.01        2.91
                ( 1 secure toggle )                    0.00     0.00        0.00
1 washer                                               0.00     0.00        0.00
                                                      $2.36     0.01       $2.91

1 Hole VS 2 Hole                    0.14 hrs
                ( 1 strap-2-grs 2-in )                 0.00     0.00        0.00
                ( 2 secure toggle )                    0.00     0.00        0.00
1 washer                                               0.00     0.00        0.00


Circ study 1/2
                50 lf-emt 1/2
                100 thhn #12


Circ study 20a
                50 lf-emt 20a


PVC vs EMT study
                1 4s vb
                1 4s-1g 5/8


PVC vs EMT study             rts    0.30 hrs
                ( Wholesale )
                ( 1 pvc 1g )


PL-220                       ax    0.75 hrs
                1 4S BOX
                1 4S-IND 1-9/16
                1 DEVICE PL-220


S3   ( 35' emt )
Raceway         35   EMT      1/2
Wire            37  3 *  THHN #14
Connectors       2   ss-con   1/2
Couplings        4   ss-coup  1/2
Nail straps      8   strap   1/2
Wire nuts        2   nut      red
Four square box  1   4S   BOX
                 1   4S   EXT
Cover Plate      2   4S-IND  SW
Device           2   device S3


65A-3P ( 3/4 4-6 )
                100 EMT     3/4
                400 THHN    #6
                11  SS-COUP 3/4
                15  STRAP   3/4


Range 50 LF-emt
                1 C-B 50A
1/2 Will Fit    50 LF-EMT 3/4
                2 ss-con 3/4
                1 4s box
                50 3 * THHN #8
                1 Device-220 Dryer
                1 4s-ind 2-1/8


Dryer 50 LF-emt
Circuit breaker 1 C-B 30A
The raceway     50 LF-EMT 1/2
The connectors  2 ss-con 1/2
The box         1 4s box
The wire        50 3 * THHN #10
The plug        1 Device-220 Dryer
Cover           1 4s-ind 2-1/8


PR EMT is 66%
Raceway         20   EMT      1/2
Connectors       2   ss-con   1/2
Couplings        3   ss-coup  1/2
Nail straps      4   strap    1/2
Four square box  1   4S       BOX


PR Wire is 33%
Wire            45   THHN     #12
Wire nuts        2   nut      red
Indust cover     1   4S-ind   pr
Easy gr. plug    1   device   pr


Total Estimate

