Finish work                                                     
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Outlet                1.87 Parts    0.20 hrs     11.27          
                1 device pr                       6.17          
                1 plate pr                        5.10          
Allready done   0 nut red                                 11.27 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Halogen-7" IC                
                1 Halo H7-ICT                  
                1 halo 310P                    
                1 Lamp 75W-PAR                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


