Fish-in-walls  either Romex or MC  (See also Romex.mod)
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                  2.77         2.21             
                                                  0.55         0.36             
                                                415.50                          
                                                415.50       145.27             
                                                  0.00         0.00             
                                                                
                                                                
                                                                
                                                                


\ Loader                                            05-19-93 AEC
Have Fish-in-walls 0= if Vocabulary Fish-in-walls then          
Fish-in-walls Definitions                                       
: Open\close-Rock   0.00 w/c   60 c ;                           
: Redo-junction                                                 
: Mount-IC          0.00 w/c   40 c ;                           
: Tape-IC           5.00 w/c   50 c ;                           
: Painting          1.00 w/c   50 c ;                           
Elect                                                           
                                                                
                                                                
Mount-IC
Tarps            5 minutes electrician                     0.08       12.00               
Open Rock       15 minutes electrician                     0.25       37.50               
Mount can       15 minutes electrician                     0.25       37.50               
Wire MC         15 minutes electrician                     0.25       37.50               
Inspection      10 minutes electrician                     0.17       25.50
                                                           1.00     $150.00               
                                               
Open/Close-Rock              
Tarps            5 minutes electrician                     0.08       12.00               
Rock up         30 minutes electrician                     0.51       76.50
                                                           0.59      $88.50               
                                               
Tape and paint               
Tarps            5 minutes electrician                     0.08       12.00               
Tape joints     15 minutes electrician                     0.25       37.50               
Sand the mud    20 minutes electrician                     0.34       51.00               
Painting        30 minutes electrician                     0.51       76.50
                                                           1.18     $177.00               
                                               
Total Estimate                                                      $415.50     

