Fish-in-walls  either Romex or MC  (See also Romex.mod)
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                  2.77         2.21             
                                                  0.55         0.36             
                                                498.60                          
                                                498.60       174.33             
                                                  0.00         0.00             
                                                  0.00         0.00             
                                                  0.00                          
                                                                
                                                                



\ Loader                                        
Have Fish-in-walls 0= if Vocabulary Fish-in-wall
Fish-in-walls Definitions                       
: Open\close-Rock   0.00 w/c   60 c ;           
: Redo-junction                                 
: Mount-IC          0.00 w/c   40 c ;           
: Tape-IC           5.00 w/c   50 c ;           
: Painting          1.00 w/c   50 c ;           
Elect
                                                
                                                
Mount-IC
Tarps            5 minutes electrician                                     14.40          
Open Rock       15 minutes electrician                                     45.00          
Mount can       15 minutes electrician                                     45.00          
Wire MC         15 minutes electrician                                     45.00          
Inspection      10 minutes electrician                                     30.60
                                                                         $180.00          
                                               
Open/Close-Rock              
Tarps            5 minutes electrician                                     14.40          
Rock up         30 minutes electrician                                     91.80
                                                                         $106.20          
                                               
Tape and paint               
Tarps            5 minutes electrician                                     14.40          
Tape joints     15 minutes electrician                                     45.00          
Sand the mud    20 minutes electrician                                     61.20          
Painting        30 minutes electrician                                     91.80
                                                                         $212.40          
                                               
Total Estimate                                                           $498.60                    

