Fish-in-walls  either Romex or MC  (See also Romex.mod)
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                  2.77         2.21
                                                  0.34         0.27
                                                149.58
                                                149.58        52.30
                                                  0.00         0.00
                                                  0.00         0.00
                                                  0.00
                                                                
                                                                



\ Loader
Have Fish-in-walls 0= if Vocabulary Fish-in-wall
Fish-in-walls Definitions
: Open\close-Rock   0.00 w/c   60 c ;
: Redo-junction
: Mount-IC          0.00 w/c   40 c ;
: Tape-IC           5.00 w/c   50 c ;
: Painting          1.00 w/c   50 c ;
Elect


Mount-IC
Tarps            5 minutes electrician                          0.08        4.32
Open Rock       15 minutes electrician                          0.25       13.50
Mount can       15 minutes electrician                          0.25       13.50
Wire MC         15 minutes electrician                          0.25       13.50
Inspection      10 minutes electrician                          0.17        9.18
                                                                1.00      $54.00

Open/Close-Rock
Tarps            5 minutes electrician                          0.08        4.32
Rock up         30 minutes electrician                          0.51       27.54
                                                                0.59      $31.86

Tape and paint
Tarps            5 minutes electrician                          0.08        4.32
Tape joints     15 minutes electrician                          0.25       13.50
Sand the mud    20 minutes electrician                          0.34       18.36
Painting        30 minutes electrician                          0.51       27.54
                                                                1.18      $63.72

Total Estimate                                                           $149.58

