Template
address
San Francisco, CA
415
email
5 line
                                                Actual         Goal
                                      Hrs         2.87         2.29 Man Hours
                                      Dys         0.35         0.28 Man Days
                                      Tot       417.69          .16 Contract
                                      Lab       393.19       137.47 W/S Labor
                                      Mtl        24.50        12.25 Pre Tax
                                      Oth         0.00         0.00
                                      Pmt         0.00



17


Plug Recepticle fished down to EMT in basement
                137.00 per-hour                                 0.00        0.00
                Fish-in-walls                                   0.00        0.00


Upper 1/2 Fish & Trim
                 1 SW-Box cut-in                                0.42       61.54
                 0 Secure F-strap                               0.00        0.00
                 4 Romex  14/2                                  0.08       12.48
At baseboard     1 Blockage Plate                               0.75      102.75
                                                                1.25     $176.77

The trim work    Elect
                 1 Device PR                                    0.10       15.70
                 1 Plate  PR                                    0.03        4.77
                                                                0.13      $20.47

Basement ceiling
1/2 of 18        9 emt 1/2                                      0.40       59.84
                 1 4s box                                       0.30       42.46
                 1 romex blue                                   0.11       15.59
                 1 4s bl                                        0.16       23.26
                 1 ground GS                                    0.04        5.59
3/4 of 2         2 SS-Con 1/2                                   0.16       22.40
                 1 SS-Coup 1/2                                  0.04        5.78
4.83 f 36       18 THHN #12                                     0.10       20.54
1/2 of 6         3 Nut Red                                      0.18       24.99
                                                                1.49     $220.45

TOTAL ESTIMATE                                                           $417.69
                                                                       =========



