Notes                                                           
  If you are working the top floor you have an attic.  It makes 
difference if there are the following conditions                
                                                                
Heat ducting acts as a barrior                                  
Is the height sit-up or stand up?                               
Are the far corners tapered down?                               
Is there insulation?                                            
Is it littered or clear?                                        
                                                                
In old work remodel cans are quicker as you don't have to:      
  Carry the cans up there and push them along                   
  The more stuff you have to drag along the slower it is        
  Trouble lights have to be carried along too                   
                                                                
The lath does cause more work than rock ceilings  It fractures  


H-7                  29.50 +tax    0.29 hrs      54.31          
                1 Halo h7                        34.53          
                1 halo H310                                     
                1 lamp 75W-R30                    7.73          
Total                                                     54.31 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Lay in                7.27 w/e      1.95 hrs    106.82          
                New-mc                                          
                LT                               57.07          
                ( whip                                          
                1 lay-in 2x2                     49.75   106.82 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


4 Lay-in             46.24 w/e      8.12 hrs    460.37          
                Neat-EMT                                        
                (J)                             106.75          
                4 whip                          154.62          
                4 lay-in 2x2                    199.00   460.37 
115.00 ea                                                       
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Notes Lay-in                                                    
Bill says 1/2 hr each not inc whip                              
  Un carton, dispose of                                         
  Assemble, lots of little parts (bag full)                     
  Up/down Ladder or scaffolding                                 
  Lamping                                                       
  Defuser (Carefull, can crack)                                 
  Raw metal edges                                               
  May need two men to lift                                      
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Ball                                                 5-27-90 AEC
                1 ball 6-in                      10.80          
                1 ball 8-in                      14.16          
                1 ball 10-in                     39.69          
                1 ball 12-in                     43.64          
                1 ball 14-in                     57.41          
                ( ball 18-in                             165.70 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Victorian            29.00 w.s.     0.50 hrs     64.15          
                1 fixture gas-2-lamp             64.15    64.15 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Moved to Support.mod         
                0 hang-flo 8-ft                
                20 secure Jack-chain           
                 2 secure S-hook               
                 2 secure Bridal               
                 4 secure Eye-lag              
Ladder                                         
Scaffolding                                    
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Chain Hung Flo               
                1 hang-flo 8-ft                
                20 secure Jack-chain           
                 2 secure S-hook               
                 2 secure Bridal               
                 2 secure Eye-lag              
Ladder                                         
Scaffolding                                    
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Chain Hung Only  Flo         
                20 secure Jack-chain           
                 2 secure S-hook               
                 2 secure Bridal               
                 2 secure Eye-lag              
Ladder                                         
Scaffolding                                    
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


