Notes                                                           
Use flex for fishing                                            
Use MC for commercial and open work                             
                                                                
If you are using flex in new open wood then...                  
                                                                
Try pricing open flex the same as surface EMT if you are using  
 the more expensive boxes like 4S VB and a ring.                
                                                                
Use a lower price for shorter than 20 LF with a 1g box          
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Loader                                                        
WANT FLEX                                                       
NEED NAILER                                                     
.( Flex is the same work and cost as Neat-EMT )                 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Flex Whip 6' gr              
                55.00 per-hour                 
                6 flex 1/2                     
                2 flex-con  1/2                
                8 3 * thhn #12                 
                2 strap  1/2                   
                2 ground gs                    
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Fished 12' gr                
                2 flex-con 1/2                 
                3 strap  1/2                   
                12 flex 1/2                    
                13 2 * thhn #12                
Full Gr         13 1 * thhn #12                
                1 device pr                    
                1 sw-box cut-in                
                1 plate pr                     
                1 blockage plate-hard          
                1 blockage fire-block          
                                               
                                               
                                               
                                               
                                               


Fished 20' gr                
                2 flex-con 1/2                 
                5 strap  1/2                   
                20 flex 1/2                    
                21 2 * thhn #12                
Full Gr         21 1 * thhn #12                
                1 device pr                    
                1 sw-box cut-in                
                1 plate pr                     
                1 blockage plate-hard          
                1 blockage fire-block          
                                               
                                               
                                               
                                               
                                               


For new work use MC                                             
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


New 20' #12 gr               
                2 flex-con 1/2                 
                3 strap 1/2                    
                20 flex 1/2                    
                21 2 * thhn #12                
Full Gr         21 1 * thhn #12                
                1 device pr                    
                1 sw-box vb                    
                1 plate pr                     
                                               
                                               
                                               
                                               
                                               
                                               
                                               


New 12' gr SW-box            
                2 flex-con 1/2                 
                3 strap 1/2                    
                12 flex 1/2                    
                13 2 * thhn #12                
Full Gr         13 1 * thhn #12                
                1 device pr                    
                1 sw-box vb                    
                1 plate pr                     
                                               
                                               
                                               
                                               
                                               
                                               
                                               


New 12' 4S ring              
                2 flex-con 1/2                 
                3 strap 1/2                    
                12 flex 1/2                    
                13 2 * thhn #12                
                13 1 * thhn #12                
                1 device pr                    
                1 4S box                       
                1 plate pr                     
                1 4S-1G 5/8                    
                                               
                                               
                                               
                                               
                                               
                                               


New 15' sw-box w/            
                2 flex-con 1/2                 
                3 strap 1/2                    
                15 flex 1/2                    
                16 2 * thhn #12                
Full Gr         00 1 * thhn #12                
                1 device pr                    
                1 sw-box vb                    
                1 plate pr                     
                                               
                                               
                                               
                                               
                                               
                                               
                                               


New 12' sw-box w/            
                2 flex-con 1/2                 
                3 strap 1/2                    
                12 flex 1/2                    
                13 2 * thhn #12                
Full Gr         00 1 * thhn #12                
                1 device pr                    
                1 sw-box vb                    
                1 plate pr                     
                                               
                                               
                                               
                                               
                                               
                                               
                                               


New 12' gr SW-box            
Note:           ( No Permit )                  
                2 flex-con 1/2                 
                3 strap 1/2                    
                12 flex 1/2                    
                13 2 * thhn #14                
Full Gr         13 1 * thhn #14                
                1 device pr                    
                1 sw-box vb                    
                1 plate pr                     
                                               
                                               
                                               
                                               
                                               
                                               


Big Flex whip Temp power     
                ( No Permit )                  
                2 flex-con 1-in                
                3 strap 1-in                   
                10 flex 1-in                   
                15 3 * thhn #4                 
Full Gr         15 1 * thhn #4                 
                                               
                                               
                                               
                                               
get flex                                       
get strap                                      
                                               
                                               
                                               


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


                             
                1 4S box                       
                2 flex-con 1/2                 
                12 flex 1/2                    
                3 nailer 1/2                   
                26 thhn #12                    
Ground          13 thhn #12                    
                1 4S-1G 5/8                    
                1 device pr                    
                1 plate pr                     
                                               
                                               
                                               
                                               
                                               
                                               


