Grounding chart of wire sizes                       12-24-93 AEC
   .                                                            
                    Size      75                                
Feeder              Ground    deg.        Use                   
#2 or less          = 8    to 115         100                   
1 or 0              = 6       150         150                   
2/0 or 3/0          = 4       200         200                   
over 3/0 to 350 mcm = 2       310         300     0.00         0.00             
over 350 to     600 = 1/0     420         400     0.00         0.00             
                                                  0.00                          
                                                  0.00         0.00             
                                                  0.00         0.00             
                                                  0.00         0.00             
                                                  0.00                          
                                                                
                                                                



Bond hot h20
                3 ground clamp                        19.86     0.60      127.86
                4 thhn #8                              2.88     0.04       10.08
It is easy      ( use .30 hrs )                        0.00     0.00        0.00
                                                     $22.74     0.64     $137.94

Ground 15a
15a ground box                                         0.00     0.00        0.00
                10 xthhn #14
                1 ground strap
                1 ground clip


Ground box 1st
                Neat-EMT
                1 blockage Fire-Block
                1 Blockage Floor-Plate
                1 Blockage Wall
                50 THHN #6
ALong joists    0.22 hr el
Ladder work     0.37 hr el
                1 Device&Plate
                1 Ground GS
                1 Nut Red
                2 Thhn #12


get blockage
get nut
6-18-07


Ground a box
                15 thhn #14
                1 blockage fire-block
                1 ground clip
                1 ground strap


\ U-fer
                25 thhn  #4
                1 ground acorn
                1 Setup Return-Trip


\ Ground Gas
                15 thhn  #4
                1 Ground clamp


\ Ground 100A
                Best-Price
The Pipe        ( EMT 1/2
Connectors      ( RT-Con 1/2
Coupling        ( RT-coup 1/2
Ground clamps   4 ground clamp
Termination     ( Ground hub
The wire        60 thhn  #6
8-ft in earth   2 ground rod
                1 Ground lug


\ Ground 200A
The pipe        10 EMT 1/2
Rain tite con   2 RT-Con 1/2
Couplings       1 RT-coup 1/2
Rod & water     2 ground clamp
Terminations    3 Ground hub
The wire        15 thhn  #6
8-ft in earth   1 ground rod  ( 10-ft long )


\ Ground 310A
                10 EMT 3/4
                2 RT-Con 3/4
                1 RT-coup 3/4
                2 ground clamp
                3 Ground hub
                15 thhn  #2
                1 ground rod


\ Ground 520A
                10 EMT 3/4
                2 RT-Con 3/4
                1 RT-coup 3/4
                2 ground clamp
                3 Ground hub
                15 thhn  1/0
                1 ground rod


\ Ground 600up
                10 EMT 1-in
                2 RT-Con 1-in
                1 RT-coup 1-in
                2 ground clamp
                3 Ground hub
                15 thhn  3/0
                1 ground rod


Total Estimate

