                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


PR-end Same-time Notes                                          
                                                                
  The wire has to be pulled up from the meters as the heater is 
220V and the plug needs to be 110 volts.  A seperate circuit is 
not required by the code, that is just the most economical way  
to do it as it would be more work to tie it in to an existing   
circuit inside the walls.                                       
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


PR-end Same-time             
Box             1 w-m 5741                     
Offset nipple   1 os-nip 1/2                   
Plug            1 device pr                    
Cover           1 plate pr                     
Wire circuit    50 2 * thhn #12                
Circuit breaker 1 c-b 20a                      
See notes prev                                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Heat-fan                     
                Open-2x4                       
                PS                             
                1 fan Fan-Light                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Heat Fan                     
                Fish-in-walls                  
                Power                          
                Fan small                      
                4 Rx 14/2                      
                2 rx blue                      
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


