55.00 per-hour                                      12-30-90 AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ ???A                       
                1 L-B     2-in                 
                3 THHN    300mcm               
                1 NT-CON  2-IN                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 400A                       
                1 L-B     2-1/2                
                3 THHN    400MCM               
                1 NT-CON  2-1/2                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 285A                       
                1 L-B     2-in                 
                3 THHN    300mcm               
                1 NT-CON  2-IN                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 200A                       
                1 L-B     1-1/2                
                3 THHN    3/0                  
                1 NT-CON  1-1/2                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 150A                       
                1 L-B     1-1/4                
                3 THHN    1/0                  
                1 NT-CON  1-1/4                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 130A                       
                1 L-B     1-1/4                
                3 THHN    #1                   
                1 NT-CON  1-1/4                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 115A #2 in 1-in            
                1 L-B     1-in                 
                3 THHN    #2                   
                1 NT-CON  1-IN                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 110A #4 in 1-1/4           
                1 L-B     1-1/4                
                3 THHN    #4                   
                1 NT-CON  1-1/4                
Includes hole                                  
Inc cutting                                    
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 85A                        
                1 L-B     1-in                 
                3 THHN    #4                   
                1 NT-CON  1-in                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 65A                        
                1 L-B     3/4                  
                3 THHN    #6                   
                1 NT-CON  3/4                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 50A                        
                1 L-B     1/2                  
                3 THHN    #8                   
                1 NT-CON  1/2                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 30A                        
                1 L-B     1/2                  
                3 THHN    #10                  
                1 NT-CON  1/2                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


