\ An LB with wire & labor costs 28% more than a 90  88-02-07 JAP
Both the materials and the labor are more expensive, even tho   
the factory 90 uses more wire ( and gains some distance )       
                                                                
Part of it is that a LB usually requires a hole.                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 420A           271.80      4.14 47   466.38             JAP
1 L-B     3-in                                    239           
3 THHN    600mcm                                   51           
1 NT-CON  3-in                                    175           
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 380A ( 400A )  256.11      4.13 47   450.22             JAP
1 L-B     3-in                                    239           
3 THHN    500mcm                                   35           
1 NT-CON  3-in                                    175           
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 335A           168.79      3.22 47   320.13             JAP
1 L-B     2-1/2                                       180       
3 THHN    400mcm                                      15        
1 NT-CON  2-1/2                                    124          
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 285A  300mcm?   67.33      2.15 47   168.38             JAP
1 L-B     2-in                                        107       
3 THHN    300mcm                                      12        
1 NT-CON  2-IN                                      48          
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 200A            37.47      1.62 47   113.61             JAP
1 L-B     1-1/2                                    76           
3 THHN    3/0                                       7           
1 NT-CON  1-1/2                                    29           
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 150A            28.39      1.41 47    94.66             JAP
1 L-B     1-1/4                                    65           
3 THHN    1/0                                       6           
1 NT-CON  1-1/4                                    22           
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 130A            27.79      1.41 47    94.06             JAP
1 L-B     1-1/4                                    65     1.10  
3 THHN    #1                                        5     0.06  
1 NT-CON  1-1/4                                    22     0.25  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 115A            18.13      0.96 47    63.25             JAP
1 L-B     1-in                                         45       
3 THHN    #2                                           4        
1 NT-CON  1-IN                                      13          
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 85A             17.29   
1 L-B     1-in                                 
3 THHN    #4                                   
1 NT-CON  1-in                                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ LB 65A             12.05      0.77 47    48.24             JAP
1 L-B     3/4                                          35       
3 THHN    #6                                           2        
1 NT-CON  3/4                                       10          
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 50A              8.67      0.65 47    39.22             JAP
1 L-B     1/2                                          28       
3 THHN    #8                                           1        
1 NT-CON  1/2                                        8          
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LB 30A              8.43      0.64 47    38.51             JAP
1 L-B     1/2                                          28       
3 THHN    #10                                          1        
1 NT-CON  1/2                                        8          
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


