                                                      17apr87jap
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Chime system               
                1 Lo-Volt Button               
                1 Lo-Volt Chime                
                1 Lo-Volt 16-Volt              
                50 Wire   18/3                 
                20 wire   18/3                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


CATV                 30.00 W/E      2.15 hrs    155.41          
                Open-2X4                                        
                CATV                             53.57          
                Fish-in-walls                                   
                CATV                            101.84   155.41 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


CATV                  9.94 W/E      0.82 hrs     59.79          
                50 Wire RG-59                    40.50          
                1 plate bl                        5.76          
Barrel          5 dollars t&m                     4.83          
                1 4s-1g 1/2                       8.70    59.79 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


