Liquid tite whips                                     13jul87jap
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Loader                                            11-21-95 AL
Vocabulary LT-whip                                              
LT-whip definitions                                             
: 30A-3W    23.94 w/e    116 c ; \ Kreps hot tub                
: 30A       23.94 w/e    116 c ; \ Kreps hot tub                
Elect                                                           
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Whip for Atlas             
\ 3P-60A                                       
                5 LT-FLEX 3/4                  
                2 LT-CON 3/4                   
                21 THHN #6 ( Power )           
                6 THHN #8 ( Ground )           
                2 strap 3/4                    
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ LT-whip 30A 3W             
                10 LT-FLEX 1/2                 
                2 LT-CON 1/2                   
Power 2-wire    12 2 * THHN #10                
Ground          12     THHN #10                
                2 strap  1/2                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


