Meter modules                                Created 2-04-91 AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Meter-Main                   
Lots of space   1 M-M 100a                     
Plastic is ok   2 bushing 1-1/4                
4 slots saved   Panel 125a-6-12                
Thinwall is ok  1 EMT 1-1/4                    
Set screws ok   1 SS-con 1-1/4                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Back feed in panel           
Small inside    1 Meter 100a                   
Ground bushing  2 G-B 1-1/4                    
Bonding         2 ground lug                   
Pay seperate    1 C-B 100a                     
4 spaces used   1 panel 125a-8-16              
Not EMT         1 GRS 1-1/4                    
Not EMT         1 NT-con 1-1/4                 
Locking screw   1 dollars parts                
                                               
                                               
                                               
                                               
                                               
                                               
                                               


