NES-MOD
address
San Francisco, CA
(415)   
email
6 line
                                             NECA Time     Motivated men
                                                 14.97     11.97 Hours          
                                                  2.99      1.99 Days           
                                              3,709.418 Contract Agreement      
                                              2,694.600      942.16 Gross Pay   
                                              1,014.81       752.23 Pre Tax     
Parts
                Neat-EMT                                                                  
All in one pnl  1 M-P 100a-12-24                           2.50      651.90               
Breakers        4 c-b 15a                                  0.80      164.12               
Breaker         1 c-b 20a                                  0.20       41.03               
Wire            60 thhn #4                                 0.84      233.40               
Aluminum cond   12 alrc 1-1/4                              0.96      225.24               
L B             1 l-b 1-1/4                                1.10      214.26               
Weather head    1 w-h 1-1/4                                0.80      151.59               
Two hole        3 strap 1-1/4                              0.03        6.75               
Threaded coup   1 Coupling 1-1/4                           0.00        2.93               
Couple taps     3 kouple-tap 100a                          0.48      179.55               
Ground rod      1 ground rod                               1.50      288.57               
Ground hub      3 ground hub                               0.36       76.41               
Romex connector 3 2s-con 1/2                               0.33       60.30               
Ground clamp    3 ground clamp                             0.60      121.38               
Solid bare      2 thhn #6                                  0.02        5.02               
4-11/16 box     1 5s box                                   0.40       75.94               
Compression     1 NT-coup 1-1/4                            0.50      108.77               
Armored ground  20 wire armor                              0.50       99.00               
Grounding bush  1 ground-bushing 1/2                       0.40       73.82               
Romex connect   7 rx blue                                  0.77      141.05               
Pre fab 90      1 alrc-90 1-1/4                            0.60      119.08               
EMT             2 EMT 1/2                                  0.09       16.94               
Hub             1 Hub 1-1/4                                0.40       85.59               
GFI             1 Device gfi                               0.30       65.47               
Auto            (  28 miles                                                               
Hammer Drill    ( ......... )                                                             
Permit          1 Permit Panel-change                      0.00      413.10               
Setup           Setup new-job                              0.49       88.20
                                                          14.97   $3,709.41               

                                                        
Total Estimate                                                    $3,709.41     
                                                                  =========
