Parts list for a new service
Based on the ENG job                                            
                                                                
                                                                
                                                                
                                                                
                                              13.87             
                                           1.26  0.99  0.86     
                                                255.30    349.76
                                              1,106.79          
                                              1,106.79          
                                                305.14          
                                                                
                                                                
                                                           11.78     14.73      
                                                            2.94      1.96      
                                                        1,819.60                
                                                        1,325.70    463.53      
                                                          493.90                
                                                            0.00           BVE  
                                                            0.00  1,819.60      


Parts 1
All in one pnl  1 M-P 100a-12-24                                     333.00
Breakers        4 c-b 15a                                  0.80       92.12               
Breaker         1 c-b 20a                                  0.20       23.03               
Wire            60 thhn #4                                 0.84      148.20               
Aluminum cond   12 alrc 1-1/4                              0.96      125.76               
L B             1 l-b 1-1/4                                1.10      112.83               
Weather head    1 w-h 1-1/4                                0.80       79.59               
Two hole        3 strap 1-1/4                              0.03        2.97               
Threaded coup   1 Coupling 1-1/4                           0.00        2.93               
Couple taps     3 kouple-tap 100a                          0.48      136.35               
Ground rod      1 ground rod                               1.50      153.57               
Ground hub      3 ground hub                               0.36       44.01               
Romex connector 3 2s-con 1/2                               0.33       30.60               
Ground clamp    3 ground clamp                             0.60       67.38
                                                          10.50   $1,352.34               
                                               


Parts 2                      
Solid bare      2 thhn #6                                  0.02        3.22               
4-11/16 box     1 5s box                                   0.40       39.94               
Compression     1 NT-coup 1-1/4                            0.50       63.77               
Armored ground  20 wire armor                              0.50       54.00               
Grounding bush  1 ground-bushing 1/2                       0.40       37.82               
Romex connect   7 rx blue                                  0.77       71.75               
Pre fab 90      1 alrc-90 1-1/4                            0.60       65.08               
EMT             2 EMT 1/2                                  0.09        9.06               
Hub             1 Hub 1-1/4                                0.40       44.10               
GFI             1 Device gfi                               0.30       38.47               
Cover           1 Plate gfi                                0.25       40.05               
Auto            (  28 miles                                                               
Hammer Drill    ( ......... )                                                             
Permit          ( Inspection )                                                            
Setup           ( and travel )
                                                           4.23     $467.26               


TOTAL                        
                                               
                                               
                                               
                                               
                                               
                                               
    110.67                                     
    774.75                                                                                
    110.67                                                                                
    110.67                                                                                
                                               
                                               
                                               
                                               
                                               

Total Estimate                                                    $1,819.60     

