NES-MOD
address
San Francisco, CA
(415)   
email
6 line
                                             NECA Time     Motivated men
                                                 14.97        11.97urs          
                                                  2.99         1.99ys           
                                              4,198.438 Contract Agreement      
                                              2,694.600      942.16 Gross Pay   
                                              1,503.83       752.23             
                                                  0.00         0.00             
                                                  0.00       752.23 Pre Tax     


Parts                                                                                                       
                Neat-EMT                               0.00     0.00        0.00          
All in one pnl  1 M-P 100a-12-24                     299.12     2.50      749.12          
Breakers        4 c-b 15a                             29.84     0.80      173.84          
Breaker         1 c-b 20a                              7.46     0.20       43.46          
Wire            60 thhn #4                           121.80     0.84      273.00          
Aluminum cond   12 alrc 1-1/4                         77.76     0.96      250.56          
L B             1 l-b 1-1/4                           24.10     1.10      222.10          
Weather head    1 w-h 1-1/4                           11.25     0.80      155.25          
Two hole        3 strap 1-1/4  3c                      2.04     0.03        7.44          
Threaded coup   1 Coupling 1-1/4                       4.35     0.00        4.35          
Couple taps     3 kouple-tap 100a                    138.00     0.48      224.40          
Ground rod      1 ground rod                          27.52     1.50      297.52          
Ground hub      3 ground hub                          17.22     0.36       82.02          
Romex connector 3 2s-con 1/2                           1.32     0.33       60.72          
Ground clamp    3 ground clamp                        19.86     0.60      127.86          
Solid bare      2 thhn #6                              2.12     0.02        5.72          
4-11/16 box     1 5s box                               5.84     0.40       77.84          
Compression     1 NT-coup 1-1/4                       27.82     0.50      117.82          
Armored ground  20 wire armor                         13.40     0.50      103.40          
Grounding bush  1 ground-bushing 1/2                   2.70     0.40       74.70          
Romex connect   7 rx blue                              3.64     0.77      142.24          
Pre fab 90      1 alrc-90 1-1/4                       16.41     0.60      124.41          
EMT             2 EMT 1/2                              1.12     0.09       17.32          
Hub             1 Hub 1-1/4                           20.14     0.40       92.14          
GFI             1 Device gfi                          17.00     0.30       71.00          
Auto            (  28 miles                            0.00     0.00        0.00          
Hammer Drill    ( ......... )                          0.00     0.00        0.00          
Permit          1 Permit Panel-change                612.00     0.00      612.00          
Setup           Setup new-job                          0.00     0.49       88.20
                                                  $1,503.83    14.97   $4,198.43          

Total Estimate                                                         $4,198.43                    
                                                                  =========
