Offset Nipple with           
                106.00 per-hour                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 20A #12    1/2             
                1  OS-NIP    1/2               
                10 THHN      #12               
                2  L-N       1/2               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 30A #10    3/4             
                1  OS-NIP    3/4               
                10 THHN      #10               
                1  GR-BUSH   3/4   ( plastic ) 
                1  Bushing   3/4               
                2  L-N       3/4               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 50A #8    1-in             
                1  OS-NIP    1-in              
                10 THHN      #8                
                1  GR-BUSH   1-in   ( plastic  
                1  Bushing   1-in              
                2  L-N       1-in              
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 65A #6   1-1/4             
                55.00 per-hour                 
                1  OS-NIP    1-1/4             
                10 THHN      #6                
                1  GR-BUSH   1-1/4             
                1  Bushing   1-1/4             
                2  L-N       1-1/4             
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 85A #4   1-1/4             
                1  OS-NIP    1-1/4             
                10 THHN      #4                
                1  GR-BUSH   1-1/4             
                1  bushing   1-1/4             
                2  L-N       1-1/4             
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 115A #2  1-1/4             
                55.00 per-hour                 
Offset nipple   1  OS-NIP    1-1/4             
The wire        10 THHN      #2                
Bonding         1  GR-BUSH   1-1/4             
Plastic         1  BUSHING   1-1/4             
Lock Nuts       2  L-N       1-1/4             
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 130A #1  1-1/4             
                1  OS-NIP    1-1/4             
                10 THHN      #1                
                1  GR-BUSH   1-1/4             
                1  Bushing   1-1/4             
                2  L-N       1-1/4             
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 150A #0  1-1/2             
                1  OS-NIP    1-1/2             
                4 3 * THHN   1/0               
                1  GR-BUSH   1-1/2             
                1  Bushing   1-1/2             
                2  L-N       1-1/2             
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 200A 3/0 1-1/2             
                1  OS-NIP    1-1/2             
                5 3 * THHN   3/0               
                1  GR-BUSH   1-1/2             
                1  Bushing   1-1/2             
                1  L-N       1-1/2             
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 285A 300mcm                
                1  OS-NIP    2-in              
                6 3 * THHN   300MCM            
                1  GR-BUSH   2-in              
                1  bushing   2-in              
                2  L-N       2-in              
                ( 2-1/2 for ease but not made  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 400A 1P 6W                 
                1  OS-NIP    3-in              
                6 6 * THHN   3/0               
                1  GR-BUSH   3-in              
                1  bushing   3-in              
                2  L-N       3-in              
                ( 2-1/2 not made 3-in easier ) 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 600A 1P 6W                 
                1  OS-NIP    3-in              
6 Wires         7 6 * THHN   300mcm            
                1  BOND-BUSH 4-in              
                1  bushing   4-in              
                2  L-N       4-in              
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 400A 3Phayse               
                1  OS-NIP    3-in              
6 wires         5 6 * THHN   500mcm ( 6 wires  
                1  GR-BUSH   3-in   ( bonding  
                1  bushing   3-in   ( plastic  
                2  L-N       3-in              
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


