                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Circuits             85.70 Parts    6.05 hrs    370.05          
                50 lf-emt 20a                   178.35          
9 wires         5 circ ( +1 = 6 )               191.70   370.05 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Sub panel           126.21 Parts    5.55 hrs    387.06          
                1 panel 125a-8-16               118.17          
                50 lf-emt 30a                   229.05          
                1 c-b 50a                        39.84   387.06 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


w/s Circuits         65.00 Parts    6.05 hrs     65.00          
                50 lf-emt 20a                    35.00          
9 wires         5 circ ( +1 = 6 )                30.00    65.00 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


w/s Sub panel        99.05 Parts    5.55 hrs     99.05          
                1 panel 125a-8-16                29.00          
                50 lf-emt 30a                    57.50          
                1 c-b 50a                        12.55    99.05 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Panel prices                                         2-19-90 AEC
                1 panel 40A-2-4                  68.72          
                1 panel 70A-2-4                  91.10          
                1 panel 125A-8-16               121.17          
                1 panel 125A-12-24              162.88          
                1 panel 125A-16-24              194.09          
                1 panel 150A-16-30              218.05          
                1 panel 150A-20-30              244.47          
                1 panel 150A-24-30              244.47          
                1 panel 200A-30-40              326.50          
                1 panel 200A-40-40              482.43          
                ( panel 400A-24-42                              
                1 panel DEAD-FRONT               29.58 2,183.46 
                                                                
                                                                
                                                                


