Residental Price List  as of date -->               02-13-00 AL
PRICES.MOD is the file name
                                                                
3-COLUMN
2-COLUMN                                                                
                                                                
                                                                
                                                251.57    201.25                
                                                 50.31     33.54                
                                              29,638.97                         
                                              20,754.28    7,256.74             
                                              8,884.69     6,581.54             
                                                        
                                                        
                                                        
                                                        


Setup                        
                Setup Job                                  0.75       61.87               
                Travel Medium                              0.75       61.87
                                                           1.50     $123.74               
                                               
\ Contingency                                           
10 percent until the inspector leaves. ..
                                                        
                                                        
Fish-In-Walls                
                82.50 per-hour                                                            
                Fish-in-walls                                                             
                LT                                         3.00      255.95               
                 LT-medium                                 2.00      173.30               
                 LT-easy                                   1.00       90.80               
                PL                                         2.75      235.32               
                 PL-medium                                 1.75      152.67               
                 PL-easy                                   1.10       99.05               
                SW                                         2.75      235.32               
                 SW-medium                                 1.75      152.82               
                 SW-easy                                   1.00       90.95               
                S3                                         3.00      255.95               
                CB  Circuit                                0.90       93.15
                                                          21.00   $1,835.28               
                                               
Neat-EMT Outlets             
                Neat-EMT                                                                  
Plaster NIC     LT                                         2.06      186.04               
                 LT-medium                                 1.70      153.75               
                 LT-easy                                   1.25      115.27               
Paint NIC       PL                                         1.75      171.05               
                 PL-medium                                 1.40      129.00               
                 PL-easy                                   1.00       94.65               
                SW                                         1.75      171.05               
                 SW-medium                                 1.70      153.75               
                 SW-easy                                   1.00       94.65               
                S3                                         2.13      193.43
                                                          15.74   $1,462.64               


Open-1-Side (2-sides)
                Open-1-side                                                               
                LT                                         0.98       86.37               
                SW                                         0.85       75.64               
                PL                                         0.85       75.64               
                S3                                         0.98       86.37               
                S4                                         0.98       88.95               
Don't use this  Open-2-sides                                                              
                LT                                         0.78       69.87               
                SW                                         0.68       61.62               
                PL                                         0.68       61.62               
                S3                                         0.78       69.87               
                S4                                         0.78       72.45
                                                           8.34     $748.40               

Big-holes-ok
Jerome 45 55    ( Jul 97 )                                                                
                Big-holes-OK                                                              
                LT                                         2.00      170.52               
                SW                                         2.00      170.92               
                PL                                         2.00      170.92               
                S3                                         2.00      170.52               
                S4                                         2.25      193.72
                                                          10.25     $876.60               
                                               
Grounding                    
                Fish-in-walls                                                             
                Ground 100a                                4.82      468.64               
                Ground box                                 3.00      254.72               
                Ground box-medium                          2.00      172.22               
                Ground Box-easy                            1.00       85.67               
                Ground rod                                 1.50      142.32               
                Ground Clip                                0.01        1.00               
                Ground box                                 3.00      254.72               
                Ground box-medium                          2.00      172.22               
                Ground box-easy                            1.00       85.67               
                Ground Bond                                0.50       50.74
                                                          18.83   $1,687.92               
                                               
GFI                          
                Fish-in-walls                                                             
                GFI                                        0.25       38.17               
                GFCI                                       0.05       21.67               
                Box-only                                   1.00       87.21               
                CATV                                       2.75      253.87               
                Fixture Motion-sensor                      0.40       73.50               
                Circuit                                    0.70       71.25               
                FPE 20A                                    0.20       50.25               
                CB                                         0.20       21.90               
                C-B 20A                                    0.20       21.53               
Up to 60A       C-B 20A-2P                                 0.30       38.25               
                C-B 100A                                   0.80      114.60
                                                           6.85     $792.20               
                                               
Fixtures                     
                Fish-in-walls                                                             
                Fixture Motion-sensor                      0.40       73.50               
                2 Lamp 75W-par                             0.12       36.62               
                Ball 6-in                                  0.25       34.12               
                Ball 8-in                                  0.25       34.78               
                Lamp 75W-par                               0.06       18.31               
                Lamp mr-16                                 0.08       10.65               
                Install easy                               0.35       28.87               
                Install medium                             0.55       45.37               
                Install pendant                            0.75       61.87               
                Install Chandelier                         1.50      123.75
                                                           4.31     $467.84               
                                               
LED
                LED                                                                       
                Rewire-LED 48-inch                         0.25       40.87               
                1 LED  4-ft                                1.25      125.80               
                2 LED  4-ft                                2.50      251.61
                                                           4.00     $418.28               
                                               
LF and Low Volt              
                Fish-in-walls                                                             
                Low-volt chime-Kit                         0.50       52.72               
                Low-volt button                            0.25       24.26               
                Low-volt tri-volt                          0.20       36.75               
                PH                                         2.75      235.32               
                SP                                         2.75      235.32               
                CATV                                       2.75      253.87
                                                           9.20     $838.24               
                                               
Fan/Heat                     
                Fish-in-walls                                                             
                Fan Small                                  0.35       51.14               
                Fan Panasonic-wall                         0.40      390.75               
                Heat Bath-1500W                            1.00      163.50               
                Heat Thermostat                            0.30       54.45               
                Heat Marly                                 1.00      240.97
                                                           3.05     $900.81               
                                               
Devices/Plate/Dimmer         
Round nob       Dimmer D-600                               0.25       34.12               
Toggle slider   Dimmer AY-600                              0.25       38.17               
Sideways toggle Dimmer DV-600                              0.25       48.97               
                D&P                                        0.12       12.42               
                Device&Plate                               0.25       23.14               
                Device-220 Dryer                           0.20       35.40               
                GFI                                        0.25       38.17
                                                           1.57     $230.39               
                                               
Big-Holes-Ok                 
Rock by others  Big-holes-ok                                                              
Light           LT                                         2.00      170.52               
Switch          SW                                         2.00      170.92               
Plug            PL                                         2.00      170.92
                                                           6.00     $512.36               
                                               
Open-2-Sides                 
(New walls)     Open-2-sides                                                              
Light           LT                                         0.78       69.87               
Plug            PL                                         0.68       61.62               
Switch          SW                                         0.68       61.62
                                                           2.14     $193.11               
                                               
Neat-Wiremold                
                Neat-Wiremold                                                             
                LT                                         2.00      205.09               
                LT-medium                                  1.50      155.50               
                LT-easy                                    1.25      123.00               
                PL                                         2.00      205.09               
                PL-medium                                  1.50      155.50               
                PL-easy                                    1.00      102.38               
                SW                                         2.00      205.09               
                SW-medium                                  1.50      155.50               
                SW-easy                                    1.00      102.38
                                                          13.75   $1,409.53               
                                               
Service 100A  #4 1-1/4       
-- NEW SERVICE  ( 230 Volts 100 Amps )                                                    
Ladder & 220V   1 Setup     Hot-220                        1.50      123.75               
To PG&E wires   1 Riser     100A                           3.57      398.95               
Conduit body    1 LB-Inc    100A                           0.96       97.19               
90 Corner bend  1 90-Inc    100A-ez                        0.30       42.70               
Meter & Panel   1 M-P       100A-12-24                     2.50      408.15               
Gr rod & water  1 Ground    100A                           4.82      468.64               
Hot cold & gas  1 Ground    BOND                           0.50       50.74
                                                          14.15   $1,590.12               
                                               
Reconnect old                
Nob & Tube wire 1 Reconnect Black-box                      1.25      108.52               
1/2 inch pipe   1 Reconnect 1/2                            1.02       95.32               
3/4 inch pipe   1 Reconnect 3/4                            1.25      116.62               
1-in pipe       1 Reconnect 1-in                           1.40      135.75               
15A Breakers    1 CB                                       0.20       21.90               
20A Breakers    1 CB                                       0.20       21.90               
30 Amp Dryer    1 C-B 30A                                  0.30       55.23               
50 Amp Range    1 C-B 50A                                  0.30       55.23               
Light at meter  Neat-EMT  LT-easy                          1.25      115.27
                                                           7.17     $725.74               
                                               
City Inspection              
Loss-prevention  ( Permit Survey-first                                                    
Meet Inspector   1 Appointment Inspector                   2.00      165.00               
Residential Lg.  1 Permit 20-outlets-2                     0.00      330.75               
OK to cover up   1 Permit Reinspection                     0.00      229.50               
Commercial mini  1 Permit 20-Commercial-3                  0.00      353.68               
Residential Sm.  1 Permit 20-Outlets-1                     0.00      120.83
                                             $             2.00   $1,199.76               
                                               
Kill                         
                Kill old-box                               0.20       16.50               
                Kill old-fixture                           0.25       20.62               
                Kill old-heater                            0.50       41.25               
                Kill old-riser                             0.75       61.87
                                                           1.70     $140.24               
                                               
Panels
                Panel                                                                     
                 70A-2-4                                   1.00      102.75               
                100A-2-2                                   1.00      110.85               
                125A-4-8                                   1.00      112.20               
                125A-6-12                                  1.25      139.57               
                125A-8-16                                  1.50      169.65               
                125A-12-24                                 2.00      227.10               
                125A-16-24                                 2.20      263.17               
                150A-16-32                                 2.40      295.20               
                150A-20-30                                 2.60      321.15               
                200A-20-40                                 3.40      488.73               
                200A-24-40                                 3.40      515.73               
                200A-30-40                                 3.40      443.85               
                200A-12-24                                 2.50      263.89               
                200A-20-40                                 3.40      488.73               
                200A-30-40                                 3.40      443.85               
                200A-40-40                                 3.50      491.25               
                225A-42-42                                 3.80      584.85               
                400A-30-40                                 5.20      672.00               
                Dead-Front                                 0.50       45.30
                                             $            47.45   $6,179.82               

               
Linear foot NeatDead-Front EMT
                1 LF-EMT   20A                             0.06        5.61               
                1 LF-EMT   30A                             0.07        6.61               
                1 LF-EMT   50A                             0.08        8.13               
                1 LF-EMT  100A                             0.12       14.15               
                1 LF-EMT  200A                             0.16       21.85               
                C-B       100A                             0.80      114.60               
                LB-Inc    100A                             0.96       97.19               
                Setup  Hot-220                             1.50      123.75               
                Riser     100A                             3.57      398.95               
                M-P 100A-12-24                             2.50      408.15               
                Ground    100A                             4.82      468.64               
                Ground    BOND                             0.50       50.74
                                                          15.14   $1,718.37               
                                               
Off set nipples              
                OS-Nip     15A                             0.31       29.28               
                OS-Nip     20A                             0.31       29.28               
                OS-Nip     30A                             0.83       79.51               
                OS-Nip     40A                             0.95       88.63               
                OS-Nip     50A                             0.95       88.63               
                OS-Nip     65A                             1.12      108.34               
                OS-Nip     85A                             1.14      112.28               
                OS-Nip    100A                             1.18      120.31               
                OS-Nip    125A                             1.20      125.47               
                OS-Nip    200A                             1.54      176.71               
                OS-Nip    400A                            10.00    1,620.15
                                                          19.53   $2,578.59               
                                               
Breakers Interchangable      
                C-B 20A                                    0.20       21.53               
Up to 60A       C-B 20A-2P                                 0.30       38.25               
Double wafer    C-B 20A-20A                                0.30       35.96               
Quad            C-B 20-20-20-20                            0.40       62.70               
                C-B 30A                                    0.30       55.23               
                C-B 40A                                    0.30       55.23               
                C-B 50A                                    0.30       55.23               
                C-B 60A                                    0.30       55.23               
                C-B 70A                                    0.60       83.92               
                C-B 90A                                    4.00      500.10               
                C-B 100A                                   0.80      114.60               
                C-B 125A                                   1.00      185.77
                                                           8.80   $1,263.75               
                                               
Breakers Square-D            
                Square-D  20A                              0.30       36.90               
Up to 60A       Square-D  20A-2P                           0.30       49.05               
                Square-D  30A                              0.30       49.05               
                Square-D  40A                              0.30       49.05               
                Square-D  50A                              0.30       58.50               
                Square-D  90A                              0.90      199.34               
                Square-D  200A                             1.00      352.50
                                                           3.40     $794.39               
                                               
Breakers FPE                 
7               FPE 20A                                    0.20       50.25               
Up to 60A       FPE 20A-2P                                 0.30       80.10               
                FPE 30A                                    0.30       80.10               
                FPE 40A                                    0.30       80.10               
                FPE 50A                                    0.30       80.10               
                FPE 60A                                    0.30       80.10               
                FPE 100A                                   4.00      500.10
                                                           5.70     $950.85               
                                               
Total Estimate                                                   $29,638.97     

