Residental Price List  as of date -->               02-13-00 AL
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Setup                        
                Setup Job                      
                Travel Medium                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Contingency                                                     
10 percent until the inspector leaves. ..                       
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Fish-In-Walls                
                82.50 per-hour                 
                Fish-in-walls                  
                LT                             
                 LT-medium                     
                 LT-easy?                      
                PL                             
                 PL-medium                     
                 PL-easy?                      
                SW                             
                 SW-medium                     
                 SW-easy?                      
                S3                             
                CB  Circuit                    
                                               
                                               


Neat-EMT Outlets             
                Neat-EMT                       
Plaster NIC     LT                             
                 LT-medium                     
                 LT-easy?                      
Paint NIC       PL                             
                 PL-medium                     
                 PL-easy?                      
                SW                             
                 SW-medium                     
                 SW-easy?                      
                S3                             
                                               
                                               
                                               
                                               


Open-1-Side (2-sides)        
                Open-1-side                    
                LT                             
                SW                             
                PL                             
                S3                             
                S4                             
Don't use this  Open-2-sides                   
                LT                             
                SW                             
                PL                             
                S3                             
                S4                             
                                               
                                               
                                               


Big-holes-ok                 
Jerome 45 55    ( Jul 97 )                     
                Big-holes-OK                   
                LT                             
                SW                             
                PL                             
                S3                             
                S4                             
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Grounding                    
                Fish-in-walls                  
                Ground 100a                    
                Ground box                     
                Ground box-medium              
                Ground Box-easy?               
                Ground rod                     
                Ground Clip                    
                Ground box                     
                Ground box-medium              
                Ground box-easy?               
                Ground Bond                    
                                               
                                               
                                               
                                               


GFI                          
                Fish-in-walls                  
                GFI                            
                GFCI                           
                Box-only                       
                CATV                           
                Fixture Motion-sensor          
                Circuit                        
                FPE 20A                        
                CB                             
                C-B 20A                        
Up to 60A       C-B 20A-2P                     
                C-B 100A                       
                                               
                                               
                                               


Fixtures                     
                Fish-in-walls                  
                Fixture Motion-sensor          
                2 Lamp 75W-par                 
                Ball 6-in                      
                Ball 8-in                      
                Lamp 75W-par                   
                Lamp mr-16                     
                Install easy?                  
                Install medium                 
                Install pendant                
                Install Chandelear             
                                               
                                               
                                               
                                               


Flo                          
                1 Flo 4-ft                     
                1 flo-wrap 4-ft                
                1 flo-wrap 4x4                 
                1 tube 4-ft                    
                4 tube 4-ft                    
                1 Warm-Tube 4-ft               
                Flo 4-ft 2 tube 4-ft           
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


LF and Low Volt              
                Fish-in-walls                  
                Low-volt chime-Kit             
                Low-volt button                
                Low-volt tri-volt              
                PH                             
                SP                             
                CATV                           
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Fan/Heat                     
                Fish-in-walls                  
                Fan Small                      
                Fan Quiet                      
                Heat Bath-1500W                
                Heat Thermostat                
                Heat Register                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Devices/Plate/Dimmer         
Round nob       Dimmer D-600                   
Toggle slider   Dimmer AY-600                  
Sideways toggle Dimmer DV-600                  
                D&P                            
                Device&Plate                   
                Device-220 Dryer               
                GFI                            
                byep                           
                exit                           
                bye                            
                                               
                                               
                                               
                                               
                                               


Big-Holes-Ok                 
Rock by others  Big-holes-ok                   
Light           LT                             
Switch          SW                             
Plug            PL                             
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Open-2-Sides                 
(New walls)     Open-2-sides                   
Light           LT                             
Plug            PL                             
Switch          SW                             
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Neat-Wiremold                
                Neat-Wiremold                  
                LT                             
                LT-medium                      
                LT-easy?                       
                PL                             
                PL-medium                      
                PL-easy?                       
                SW                             
                SW-medium                      
                SW-easy?                       
                                               
                                               
                                               
                                               
                                               


Service 100A  #4 1-1/4       
-- NEW SERVICE  ( 230 Volts 100 Amps )         
Ladder & 220V   1 Setup     Hot-220            
To PG&E wires   1 Riser     100A               
Conduit body    1 LB-Inc    100A               
90 Corner bend  1 90-Inc    100A-ez?           
Meter & Panel   1 M-P       100A-12-24         
Gr rod & water  1 Ground    100A               
Hot cold & gas  1 Ground    BOND               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Reconnect old                
Nob & Tube wire 1 Reconnect Black-box          
1/2 inch pipe   1 Reconnect 1/2                
3/4 inch pipe   1 Reconnect 3/4                
1-in pipe       1 Reconnect 1-in               
15A Breakers    1 CB                           
20A Breakers    1 CB                           
30 Amp Dryer    1 C-B 30A                      
50 Amp Range    1 C-B 50A                      
Light at meter  Neat-EMT  LT-easy?             
                                               
                                               
                                               
                                               
                                               
                                               


City Inspection              
Residential Sm.  1 Permit 20-Outlets-1   (     
Meet Inspector   1 Appointment Inspector (     
Residential Lg.  1 Permit 2-Inspections  (     
OK to cover up   1 Permit Reinspection   (     
Commercial mini  1 Permit 5-Commercial   (     
Commercial big   1 Permit 6+Commercial   (     
Loss-prevention  1 Permit Survey-first   (     
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Kill                         
                Kill old-box                   
                Kill old-fixture               
                Kill old-heater                
                Kill old-riser                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Panels                     1,
                Panel  70A-2-4               2 
                Panel 100A-2-2                 
                Panel 125A-4-8                 
                Panel 125A-6-12                
                Panel 125A-8-16                
                Panel 125A-12-24               
                Panel 125A-16-24               
                Panel 150A-16-30               
                Panel 150A-20-30               
                Panel 150A-24-30               
                Panel 200A-12-24               
                Panel 200A-30-40               
                Panel 200A-40-40               
                Panel 200A-30-40               
                Panel 225A-42-42               


Linear foot Neat EMT         
                1 LF-EMT   20A                 
                1 LF-EMT   30A                 
                1 LF-EMT   50A                 
                1 LF-EMT  100A                 
                1 LF-EMT  200A                 
                C-B       100A                 
                LB-Inc    100A                 
                Setup  Hot-220                 
                Riser     100A                 
                M-P 100A-12-24                 
                Ground    100A                 
                Ground    BOND                 
                                               
                                               
                                               


Off set nipples              
                OS-Nip     15A                 
                OS-Nip     20A                 
                OS-Nip     30A                 
                OS-Nip     40A                 
                OS-Nip     50A                 
                OS-Nip     65A                 
                OS-Nip     85A                 
                OS-Nip    100A                 
                OS-Nip    125A                 
                OS-Nip    200A                 
                OS-Nip    400A                 
                                               
                                               
                                               
                                               


Breakers Interchangable      
                C-B 20A                        
Up to 60A       C-B 20A-2P                     
Double wafer    C-B 20A-20A                    
Quad            C-B 20-20-20-20                
                C-B 30A                        
                C-B 40A                        
                C-B 50A                        
                C-B 60A                        
                C-B 70A                        
                C-B 90A                        
                C-B 100A                       
                C-B 125A                       
                                               
                                               
                                               


Breakers Square-D            
                Square-D  20A                  
Up to 60A       Square-D  20A-2P               
                Square-D  30A                  
                Square-D  40A                  
                Square-D  50A                  
                Square-D  90A                  
                Square-D 200A                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Breakers FPE                 
7               FPE 20A                        
Up to 60A       FPE 20A-2P                     
                FPE 30A                        
                FPE 40A                        
                FPE 50A                        
                FPE 60A                        
                FPE 100A                       
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


