Residental Price List  as of date -->               02-13-00 AL
PRICES.MOD is the file name
                                                                
3-COLUMN
2-COLUMN                                                                
                                                                
                                                                
                                                231.93       185.54
                                                 28.99        23.19
                                             43,761.457
                                             31,554.198   11,032.93
                                             12,207.26     6,103.61
                                                  0.00         0.00
                                                  0.00
                                                        
                                                        



Setup
                Setup Job                                       0.75       61.87
                Travel Medium                                   0.75       61.87
                                                                1.50     $123.74

\ Contingency
10 percent until the inspector leaves. ..


Fish-In-Walls
                136.40 per-hour                                 0.00        0.00
                Fish-in-walls                                   0.00        0.00
                LT                                              3.00      421.72
                 LT-medium                                      2.25      319.20
                 LT-easy                                        1.00      148.70
                PL                                              2.75      387.62
                 PL-medium                                      2.25      319.20
                 PL-easy                                        1.10      162.34
                SW                                              2.75      391.10
                 SW-medium                                      1.75      253.22
                 SW-easy                                        1.00      148.92
                S3                                              3.00      421.72
                CB  Circuit                                     0.90      148.76
                                                               21.75   $3,122.50

Neat-EMT Outlets
                Neat-EMT                                        0.00        0.00
Plaster NIC     LT                                              2.06      304.82
                 LT-medium                                      1.70      251.88
                 LT-easy                                        1.25      188.50
Paint NIC       PL                                              1.75      278.24
                 PL-medium                                      1.40      210.96
                 PL-easy                                        1.00      154.40
                SW                                              1.75      278.24
                 SW-medium                                      1.70      251.88
                 SW-easy                                        1.00      154.40
                S3                                              2.13      316.77
                                                               15.74   $2,390.09

Open-1-Side (2-sides)
                Open-1-side                                     0.00        0.00
                LT                                              0.98      141.85
                SW                                              0.85      124.12
                PL                                              0.85      124.12
                S3                                              0.98      141.85
                S4                                              0.98      145.67
Don't use this  Open-2-sides                                    0.00        0.00
                LT                                              0.78      114.57
                SW                                              0.68      100.93
                PL                                              0.68      100.93
                S3                                              0.78      114.57
                S4                                              0.78      118.39
                                                                8.34   $1,227.00

Big-holes-ok
Jerome 45 55    ( Jul 97 )                                      0.00        0.00
                Big-holes-OK                                    0.00        0.00
                LT                                              2.00      280.98
                SW                                              2.00      281.58
                PL                                              2.00      281.58
                S3                                              2.00      280.98
                S4                                              2.25      318.90
                                                               10.25   $1,444.02

Grounding
                Fish-in-walls                                   0.00        0.00
                Ground 100a                                     4.82      762.62
                Ground box                                      3.00      419.90
                Ground box-medium                               2.00      283.50
                Ground Box-easy                                 1.00      141.10
                Ground rod                                      1.50      232.12
                Ground Clip                                     0.01        1.63
                Ground box                                      3.00      419.90
                Ground box-medium                               2.00      283.50
                Ground box-easy                                 1.00      141.10
                Ground Bond                                     0.50       82.26
                                                               18.83   $2,767.63

GFI
                Fish-in-walls                                   0.00        0.00
                GFI                                             0.25       60.10
                GFCI                                            0.05       32.82
                Box-only                                        1.00      143.38
                CATV                                            2.75      415.10
                Fixture Motion-sensor                           0.40      114.56
                Circuit                                         0.70      115.48
                FPE 20A                                         0.20       77.28
                CB                                              0.20       33.28
                C-B 20A                                         0.20       36.44
Up to 60A       C-B 20A-2P                                      0.30       60.92
                C-B 100A                                        0.80      181.12
                                                                6.85   $1,270.48

Fixtures
                Fish-in-walls                                   0.00        0.00
                Fixture Motion-sensor                           0.40      114.56
                2 Lamp 75W-par                                  0.12       55.96
                Ball 6-in                                       0.25       54.10
                Ball 8-in                                       0.25       55.08
                Lamp 75W-par                                    0.06       27.98
                Lamp mr-16                                      0.08       16.91
                Install easy                                    0.35       47.74
                Install medium                                  0.55       75.02
                Install pendant                                 0.75      102.30
                Install Chandelier                              1.50      204.60
                                                                4.31     $754.25

LED
                \ LED                                           0.00        0.00
                \ Rewire-LED 48-inch                            0.00        0.00
                \ 1 LED  4-ft                                   0.00        0.00
                \ 2 LED  4-ft                                   0.00        0.00


LF and Low Volt
                Fish-in-walls                                   0.00        0.00
                Low-volt chime-Kit                              0.50       85.20
                Low-volt button                                 0.25       39.50
                Low-volt tri-volt                               0.20       57.28
                PH                                              2.75      387.62
                SP                                              2.75      387.62
                CATV                                            2.75      415.10
                                                                9.20   $1,372.32

Fan/Heat
                Fish-in-walls                                   0.00        0.00
                Fan Small                                       0.35       80.74
                Fan Panasonic-wall                              0.40      584.56
                Heat Bath-1500W                                 1.00      256.40
                Heat Thermostat                                 0.30       84.92
                Heat Marly                                      1.00      371.18
                                                                3.05   $1,377.80

Devices/Plate/Dimmer
Round nob       Dimmer D-600                                    0.25       54.10
Toggle slider   Dimmer AY-600                                   0.25       60.10
Sideways toggle Dimmer DV-600                                   0.25       76.10
                D&P                                             0.12       20.10
                Device&Plate                                    0.25       37.84
                Device-220 Dryer                                0.20       55.28
                GFI                                             0.25       60.10
                                                                1.57     $363.62

Big-Holes-Ok
Rock by others  Big-holes-ok                                    0.00        0.00
Light           LT                                              2.00      280.98
Switch          SW                                              2.00      281.58
Plug            PL                                              2.00      281.58
                                                                6.00     $844.14

Open-2-Sides
(New walls)     Open-2-sides                                    0.00        0.00
Light           LT                                              0.78      114.57
Plug            PL                                              0.68      100.93
Switch          SW                                              0.68      100.93
                                                                2.14     $316.43

Neat-Wiremold
                Wiremold                                        0.00        0.00
                LT                                              0.78      114.57
                LT-medium                                       1.50      251.64
                LT-easy                                         0.50       76.38
                PL                                              0.68      100.93
                PL-medium                                       1.50      251.64
                PL-easy                                         0.55       81.80
                SW                                              0.68      100.93
                SW-medium                                       1.50      251.64
                SW-easy                                         1.00      165.86
                                                                8.69   $1,395.39

Service 100A  #4 1-1/4
-- NEW SERVICE  ( 230 Volts 100 Amps )                          0.00        0.00
Ladder & 220V   1 Setup     Hot-220                             1.50      204.60
To PG&E wires   1 Riser     100A                                3.57    1,011.18
Conduit body    1 LB-Inc    100A                                0.96      157.60
90 Corner bend  1 90-Inc    100A-ez                             0.30       67.52
Meter & Panel   1 M-P       100A-12-24                          2.50      640.12
Gr rod & water  1 Ground    100A                                4.82      762.62
Hot cold & gas  1 Ground    BOND                                0.50       82.26
                                                               14.15   $2,925.90

Reconnect old
Nob & Tube wire 1 Reconnect Black-box                           0.91      139.24
1/2 inch pipe   1 Reconnect 1/2                                 1.02      155.68
3/4 inch pipe   1 Reconnect 3/4                                 1.25      190.50
1-in pipe       1 Reconnect 1-in                                1.40      220.96
15A Breakers    1 CB                                            0.20       33.28
20A Breakers    1 CB                                            0.20       33.28
30 Amp Dryer    1 C-B 30A                                       0.30       62.48
50 Amp Range    1 C-B 50A                                       0.30       62.48
Light at meter  Neat-EMT  LT-easy                               1.25      188.50
                                                                6.83   $1,086.40

City Inspection
Loss-prevention  ( Permit Survey-first                          0.00        0.00
Meet Inspector   1 Appointment Inspector                        2.00      272.80
Residential Lg.  1 Permit 20-outlets-2                          0.00      490.00
OK to cover up   1 Permit Reinspection                          0.00      340.00
Commercial mini  1 Permit 20-Commercial-3                       0.00      523.98
Residential Sm.  1 Permit 20-Outlets-1                          0.00      179.02
                                             $                  2.00   $1,805.80


Kill
                Kill old-box                                    0.20       27.28
                Kill old-fixture                                0.25       34.10
                Kill old-heater                                 0.50       68.20
                Kill old-riser                                  0.75      102.30
                                                                1.70     $231.88

Panels
                Panel                                           0.00        0.00
                 70A-2-4                                        1.00      166.40
                100A-2-2                                        1.00      178.40
                125A-4-8                                        1.00      180.40
                125A-6-12                                       1.25      224.50
                125A-8-16                                       1.50      272.60
                125A-12-24                                      2.00      364.80
                125A-16-24                                      2.20      421.08
                150A-16-32                                      2.40      471.36
                150A-20-30                                      2.60      512.64
                200A-20-40                                      3.40      772.26
                200A-24-40                                      3.40      812.26
                200A-30-40                                      3.40      705.76
                200A-12-24                                      2.50      426.40
                200A-20-40                                      3.40      772.26
                200A-30-40                                      3.40      705.76
                200A-40-40                                      3.50      777.40
                225A-42-42                                      3.80      920.32
                400A-30-40                                      5.20    1,069.28
                Dead-Front                                      0.50       74.20
                                             $                 47.45   $9,828.08


Linear foot NeatDead-Front EMT
                1 LF-EMT   20A                                  0.06        9.16
                1 LF-EMT   30A                                  0.07       10.79
                1 LF-EMT   50A                                  0.08       13.19
                1 LF-EMT  100A                                  0.12       22.65
                1 LF-EMT  200A                                  0.16       34.64
                C-B       100A                                  0.80      181.12
                LB-Inc    100A                                  0.96      157.60
                Setup  Hot-220                                  1.50      204.60
                Riser     100A                                  3.57    1,011.18
                M-P 100A-12-24                                  2.50      640.12
                Ground    100A                                  4.82      762.62
                Ground    BOND                                  0.50       82.26
                                                               15.14   $3,129.93

Off set nipples
                OS-Nip     15A                                  0.31       47.78
                OS-Nip     20A                                  0.31       47.78
                OS-Nip     30A                                  0.83      129.57
                OS-Nip     40A                                  1.27      194.34
                OS-Nip     50A                                  1.27      194.34
                OS-Nip     65A                                  1.12      176.38
                OS-Nip     85A                                  1.14      182.51
                OS-Nip    100A                                  1.18      194.97
                OS-Nip    125A                                  1.20      202.90
                OS-Nip    200A                                  1.54      283.63
                OS-Nip    400A                                  2.26      493.44
                                                               12.43   $2,147.64

Breakers Interchangable
                C-B 20A                                         0.20       36.44
Up to 60A       C-B 20A-2P                                      0.30       60.92
Double wafer    C-B 20-20A                                      0.30       57.54
Quad            C-B 20-20-20-20                                 0.40       98.56
                C-B 30A                                         0.30       62.48
                C-B 40A                                         0.30       62.48
                C-B 50A                                         0.30       62.48
                C-B 60A                                         0.30       62.48
                C-B 70A                                         0.60      132.84
                C-B 90A                                         4.00      797.60
                C-B 100A                                        0.80      181.12
                C-B 125A                                        1.00      289.40
                                                                8.80   $1,904.34

Breakers Square-D
                Square-D  20A                                   0.30       58.92
Up to 60A       Square-D  20A-2P                                0.30       76.92
                Square-D  30A                                   0.30       76.92
                Square-D  40A                                   0.30       76.92
                Square-D  50A                                   0.30       90.92
                Square-D  90A                                   0.90      308.08
                Square-D  200A                                  1.00      536.40
                                                                3.40   $1,225.08

Breakers FPE
7               FPE 20A                                         0.20       77.28
Up to 60A       FPE 20A-2P                                      0.30      122.92
                FPE 30A                                         0.30      122.92
                FPE 40A                                         0.30      122.92
                FPE 50A                                         0.30      122.92
                FPE 60A                                         0.30      122.92
                FPE 100A                                        0.11       15.11
                                                                1.81     $706.99

Total Estimate                                                        $43,761.45

