Designed to be both the module and the sell file    88-07-28 AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Loader                                                     AEC
Vocabulary LF-PVC   LF-PVC Definitions                          
7 EOF Thru                                                      
Elect                                                           
cr cr .( LF-PVC is now loaded in to ELECTRIC Definitions )      
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 200A-3P run      1,976.20        11.72       2,527.04      AEC
                100 PVC 2-1/2                       6           
                10 COUPLING 2-1/2                 119           
                100 4 * thhn 4/0                2,401    2,526  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 200A-3P          1,976.20        11.72       2,527.04      AEC
                100 PVC 2-1/2                       6           
                10 COUPLING 2-1/2                 119           
                100 4 * thhn 4/0                2,401           
                                                                
Special for                                                     
Grand Ave                                                       
Oversize                                                 2,526  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 100A-3P           689.10        13.20       1,309.50       AEC
                100 PVC 1-1/4                     359           
                10 COUPLING 1-1/4                  32           
                100 4 * thhn #2                   918           
                                                                
Special for                                                     
Grand Ave                                                       
Oversize                                                 1,309  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 30A ( 1Phase )    169.20         6.20        460.60        AEC
                100 PVC 3/4                       180           
                10 COUPLING 3/4                    18           
                100 4 * thhn #10                  262           
                                                                
Special for                                                     
Grand Ave                                                       
Oversize                                                        
Parking lts                                                460  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


PVC Outlet            8.94 +tax     1.56 hrs     89.73          
                Elect                                           
                10 pvc-pipe 1/2                  15.70          
                2 pvc-male 1/2                   10.66          
                1 3-oct box                      22.28          
                1 3-oct ext                      13.33          
                12 3 * thhn #14                  11.16          
                2 nut yellow                      4.10          
                1 install easy                   12.50    89.73 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Loadme                                                     AEC
  :   200A-3P           1976 ex        12 c  ; \   2,527.04     
  :   200A-3P           1976 ex        12 c  ; \   2,527.04     
  :   100A-3P            689 ex        13 c  ; \   1,309.50     
  :   30A ( 1Phase )     169 ex         6 c  ; \    460.60      
                                                                
\v                                                              
Go SO IND     or  n BLOCK 64 SO TYPE                            
Add the  :                                                      
Remove the comma and close it up, delete the decimal and cents  
Add the EX                                                      
Add the c ; \                                                   
Change the hours from decimal to interger                       
                                                                
                                                                
                                                                


