Here is a study of quad conversions.  [ no auto ]     27oct87jap
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ QUAD conversion 4                                   27oct87jap
.( Convert a 4S-1/2 box to a quad outlet ) cr                   
1 2G-RING 1/2                                      11           
1 device 270-9                                     11           
1 cover 2G                                          7           
1 thhn #12                                          0           
TOTAL  CLEAR                                                    
.( Credit these items ) cr                                      
1 SG-RING 1/2                                                   
1 cover 1-g                                                     
TOTAL CR                                                        
.( Difference s/b about $12.39 if original ) CR                 
.( was a 4S-1/2 box ) cr                                        
.( call it the same as a RE FACE price prox $16.                
                                                                
                                                                


\ QUAD conversion SWITCH BOX    $ 28.66               12SEP86JAP
.( Convert a SWITCH box in to a quad outlet ) cr                
1 4S-1/2 box                                                    
1 2G-RING 1/2                                                   
1 device 270-9                                                  
1 cover 2G                                                      
1 thhn #12                                                      
TOTAL  CLEAR                                                    
.( Credit these items ) cr                                      
1 SG-RING 1/2                                                   
1 cover 1-g                                                     
TOTAL CR                                                        
.( Difference s/b about $28.66 if original ) CR                 
.( was a switch box ) cr                                        
.( call it the same as a RE FACE price prox $16.30 )            
                                                                


\ 4S-1/2 versis SWITCH BOX is $20.57 or $10.57 ea.    12SEP86JAP
.( Compare a SWITCH box in to a 4S-1/2 outlet ) cr              
1 4S-1/2 FBC                                                    
1 SG-RING 1/2                                                   
Total Clear                                                     
                                                                
1 SW-BOX FBC                                                    
Total Clear                                                     
                                                                
1 Device 270-9                                                  
1 Cover 1G                                                      
1 THHN #12                                                      
TOTAL  CLEAR                                                    
.( Difference s/b about $20.57 ) CR                             
.( or aproximatly       $10.57 using the same box times.)       
                                                                


