Reconnections                                       03-04-90 AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


2 looms nic CB               
                7 EMT 1/2                      
                14 THHN #14                    
                2 SS-CON 1/2                   
                1 4S BOX                       
                1 4S BL                        
2 Loom each     1 Romex Large                  
                2 Nut Yellow                   
This is for                                    
one circ                                       
                                               
                                               
                                               
                                               
                                               
                                               


4 looms nic CB               
                7 EMT 1/2                      
                28 THHN #14                    
                2 SS-CON 1/2                   
                1 4S BOX                       
                1 4S BL                        
2 Loom each     2 Romex Large                  
                2 Nut Red                      
                2 Nut Yellow                   
This is for a                                  
pair of circ                                   
or 4 looms.                                    
                                               
                                               
                                               
                                               


6 looms nic CB               
                7 EMT 1/2                      
                32 THHN #14                    
                2 SS-CON 1/2                   
                1 4S BOX                       
                1 4S BL                        
2 Loom each     3 Romex Large                  
                3 Nut Red                      
                4 Nut Yellow                   
This is for a                                  
pair of circ                                   
or 4 looms.                                    
                                               
                                               
                                               
                                               


1/2 emt                      
                7 EMT 1/2                      
                33 THHN #14                    
                2 SS-CON 1/2                   
                1 4S BOX                       
                1 4S BL                        
                2 NUT RED                      
                2 NUT YELLOW                   
This is for a                                  
pair of circ                                   
in a 1/2 in                                    
existing EMT                                   
                                               
                                               
                                               
                                               


Flex                         
                0 FLEX 1/2                     
                7 3 + 6 * THHN #14             
                1 Flex-Con 1/2                 
                4 NUT RED                      
                3 NUT YELLOW                   
This is not                                    
including CB                                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


RE-CON  pair circ            
                7 EMT 1/2                      
                7 3 + 6 * THHN #14             
                2 SS-CON 1/2                   
                4 NUT RED                      
                3 NUT YELLOW                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Pair of loom                 
                7 EMT 1/2                      
                33 THHN #14                    
                1 4S BOX                       
                1 4s BL                        
                2 SS-CON 1/2                   
                2 NUT RED                      
                6 NUT YELLOW                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


3/4 emt                      
                7 EMT 3/4                      
                7 3 + 6 * THHN #14             
                2 SS-CON 3/4                   
                1 4S BOX                       
                1 4S BL                        
                2 NUT RED                      
                2 NUT YELLOW                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


1-in                         
                7 EMT 1-in                     
                7 3 + 6 * THHN #8              
                2 SS-CON 1-in                  
                1 5S BOX                       
                1 5S BL                        
                2 NUT Big-Blue                 
                2 NUT YELLOW                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Black box                    
                Neat-EMT                       
                4 EMT 1/2                      
                4 3 + 6 * THHN #14             
                2 SS-Con 1/2                   
                4 Nut Red                      
                3 Nut Yellow                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


