Recesed Cans                                                    
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


2 in reg                     
                Recesed-2" New-Non             
                Recesed-2" Trim                
                Lamp 75w-par                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


2 in IC                      
                Recesed-2" Nora-IC             
                Recesed-2" Trim                
                Lamp 75w-par                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


2 in flo (Not made)          
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


4 in reg                     
                Recesed-4" Can                 
                Recesed-4" Trim                
                Lamp 75w-par                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


4 in IC                      
                Recesed-4" Can-IC              
                Recesed-4" Trim                
50W             Lamp 75w-par                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


4 in flo        ( Not made )                                    
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


6 in reg                     
Expensive       Halo       H7                  
                Recesed-6" Trim                
                Lamp 75w-par                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


6-in IC                      
Cheep           Recesed-6" Can-IC              
                Recesed-6" Trim                
                Lamp 75w-par                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


6-in flo                     
                Flo H7-Flo                     
                Recesed-6" Trim                
                Tube 13w-Quad                  
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


