Repull an existing riser,  no pipe work at all        15mar87jap
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 1/2 50A #8      11.02 +    
                3 NUT BLUE                     
                1 W-H 1/2                      
                15 3 + *  THHN  #8             
                1 Ground-bushing 1/2           
                                               
Asumes thread                                  
right on,                                      
no extend                                      
or bend riser.) cr                             
                                               
                                               
                                               
                                               
                                               
                                               


\ 3/4 65A #6      14.04 + 1.04 hrs @ $47 = $62.92               
3 NUT BLUE                                      002             
1 W-H 3/4                                       032             
15 3 + *  THHN  #6                              001             
1 bond 3/4                                      026             
TOTAL                                                           
cr                                                              
\ asumes bolt right on,                                         
\ no extend or bend riser.) cr                                  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 1-in 100A #2    18.02 + 1.14 hrs @ $47 = $71.60               
3 NUT BLUE                                      002             
1 W-H 1-in                                      036             
15 3 + *  THHN  #2                              002             
1 BOND 1-in                                     030             
TOTAL                                                           
                                                                
\ asumes bolt right on,                                         
\ no extend or bend riser.) cr                                  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


