15 foot risers without any
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 70A #4 Repull              
                15 ALRC   3/4                  
                54 THHN   #4                   
                 3 NUT    Big-Blue             
                 1 W-H    3/4                  
                 1 NT-CON 3/4                  
Use a line item  0 L-B    3/4                  
                 5 STRAP  3/4                  
                 1 HUB    3/4                  
get nut                                        
get nt-con                                     
get hub                                        
get strap                                      
get alrc free                                  
                                               
                                               


\ 100A #4 1-1/4              
                15 ALRC   1-1/4                
                54 THHN   #4                   
                 3 NUT    Big-Blue             
                 1 W-H    1-1/4                
                 1 NT-CON 1-1/4                
                 0 L-B    1-1/4                
                 5 STRAP  1-1/4                
                 1 HUB    1-1/4                
Single family!                                 
                                               
                                               
                                               
                                               
                                               
                                               


\ 115A #2 1-1/4              
                15 ALRC   1-1/4                
                54 THHN   #2                   
                 3 NUT    Big-Blue             
                 1 W-H    1-1/4                
                 1 NT-CON 1-1/4                
                 ( L-B    1-1/4                
                 5 STRAP  1-1/4                
                 1 HUB    1-1/4                
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 150A #1 1-1/2 Res          
                15 ALRC   1-1/2                
                54 THHN   #1                   
                 3 NUT    Big-blue             
                 1 W-H    1-1/2                
                 1 NT-CON 1-1/2                
                 ( L-B    1-1/2                
                 5 STRAP  1-1/2                
                 1 HUB    1-1/2                
                                               
get nut                                        
get nt-con                                     
get l-b                                        
get hub                                        
get strap                                      
get alrc                                       


\ 175A 1/0 1-1/2             
                15 ALRC   1-1/2                
                54 THHN   1/0                  
                 3 NUT    Big-Blue             
                 1 W-H    1-1/2                
                 1 NT-CON 1-1/2                
                 ( L-B    1-1/2                
                 5 STRAP  1-1/2                
                 1 HUB    1-1/2                
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 200A 2/0 2-IN   Not in     
                15 ALRC   2-IN                 
                54 THHN   2/0                  
                 3 NUT    Big-Blue             
                 1 W-H    2-IN                 
                 1 NT-CON 2-IN                 
                 ( L-B    2-IN )               
                 5 STRAP  2-IN                 
                 1 HUB    2-IN                 
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ 300A 350MCM  2-1/2         
                15 ALRC   2-1/2                
                54 THHN   350mcm               
                 3 NUT    Big-Blue             
                 1 W-H    2-1/2                
                 1 NT-CON 2-1/2                
                 ( L-B    2-1/2 )              
                 5 STRAP  2-1/2                
                 1 HUB    2-1/2                
                                               
                                               
get nt-con                                     
get strap                                      
get hub                                        
                                               
                                               


\ 280A-3P  300MCM 3-IN  (Out of date)                           
Lower portion    10 ALRC       3-IN                             
Top portion       5 GRS        3-IN                             
Steel please      1 Coupling   3-IN                             
Copper           15 3 + 4 * THHN 300MCM                         
Less if roof      1 W-H        3-IN                             
Same as lugs      3 KOUPLE-TAP 350-2/0                          
                  ( NT-CON     3-IN                             
                  ( L-B        3-IN                             
Or strut          5 STRAP      3-IN                             
                  1 HUB        3-IN                             
                                                                
                                                                
                                                                
                                                                
                                                                


\ 380A 500MCM 3-IN      (Out of date)                           
                15 ALRC       3-IN                              
                54 THHN       500MCM                            
                 1 W-H        3-IN                              
                 3 KOUPLE-TAP 500-4                             
                 1 NT-CON     3-IN                              
                 ( L-B        3-IN
                 5 STRAP      3-IN                              
                 1 HUB        3-IN
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 420A 600MCM 3-IN      (Out of date)                        AL
                15 ALRC       3-IN                              
                54 THHN       600MCM                            
                 1 W-H        3-IN                              
                 3 KOUPLE-TAP 500-4                             
                 1 NT-CON     3-IN                              
                 ( L-B        3-IN                              
                 5 STRAP      3-IN                              
                 1 HUB        3-IN
                                                                
                                                                
                                                                

                                                                
                                                                
                                                                


200A 3/0 2-in 3P        (Out of date)                           
                15 ALRC   2-in                                  
                17 4 *  THHN 3/0                                
                 4 NUT    Big-Blue                              
                 1 W-H    2-in                                  
                 1 NT-CON 2-in                                  
                 ( L-B    2-in                                  
                 5 STRAP  2-in
                 1 HUB    2-in                                  
                                                                
                                                                
                                                                
380A 500MCM 3-IN   2-8-2012 Our Planet Earth
                15 ALRC       3-IN                         2.10      344.70               
                54 15 + THHN       500MCM                  3.03      716.37
                 1 W-H        3-IN                         1.80      251.94               
                 1 NT-CON     3-IN                         0.75      183.63               
If needed        1 L-B        3-IN                         3.25      370.51               
                 5 STRAP      3-IN                         0.05       17.70               
                 1 HUB        3-IN                         0.65       74.70
                                                          11.63   $1,959.55


