15 foot risers without any
                                               
                                               
                                               
                                               
                                               
                                               
                                                 20.36        16.28
                                                  2.54         2.03
                                              4,676.72
                                              2,443.20       854.26
                                              2,233.52     1,117.19
                                                  0.00         0.00
                                                  0.00
                                               
                                               



70A #4 Repull
                15 ALRC   3/4                         35.70     0.90      143.70
                54 THHN   #4                         109.62     0.75      199.62
                 3 NUT    Big-Blue                     1.35     0.12       15.75
                 1 W-H    3/4                          8.50     0.55       74.50
                 1 NT-CON 3/4                          5.26     0.14       22.06
Use a line item  0 L-B    3/4                          0.00     0.00        0.00
                 5 STRAP  3/4                          1.90     0.05        7.90
                 1 HUB    3/4                         12.00     0.30       48.00
get nut                                                0.00     0.00        0.00
get nt-con                                             0.00     0.00        0.00
get hub                                                0.00     0.00        0.00
get strap                                              0.00     0.00        0.00
get alrc free                                          0.00     0.00        0.00
                                                    $174.33     2.81     $511.53

\ 100A #4 1-1/4
                15 ALRC   1-1/4
                54 THHN   #4
                 3 NUT    Big-Blue
                 1 W-H    1-1/4
                 1 NT-CON 1-1/4
                 0 L-B    1-1/4
                 5 STRAP  1-1/4
                 1 HUB    1-1/4
Single family!


\ 115A #2 1-1/4
                15 ALRC   1-1/4
                54 THHN   #2
                 3 NUT    Big-Blue
                 1 W-H    1-1/4
                 1 NT-CON 1-1/4
                 ( L-B    1-1/4
                 5 STRAP  1-1/4
                 1 HUB    1-1/4


\ 150A #1 1-1/2 Res
                15 ALRC   1-1/2
                54 THHN   #1
                 3 NUT    Big-blue
                 1 W-H    1-1/2
                 1 NT-CON 1-1/2
                 ( L-B    1-1/2
                 5 STRAP  1-1/2
                 1 HUB    1-1/2


get nut
get nt-con                                             0.00     0.00        0.00
get l-b                                                0.00     0.00        0.00
get hub                                                0.00     0.00        0.00
get strap                                              0.00     0.00        0.00
get alrc                                               0.00     0.00        0.00


\ 175A 1/0 1-1/2
                15 ALRC   1-1/2
                54 THHN   1/0
                 3 NUT    Big-Blue
                 1 W-H    1-1/2
                 1 NT-CON 1-1/2
                 ( L-B    1-1/2
                 5 STRAP  1-1/2
                 1 HUB    1-1/2


\ 200A 2/0 2-IN   Not in
                15 ALRC   2-IN
                54 THHN   2/0
                 3 NUT    Big-Blue
                 1 W-H    2-IN
                 1 NT-CON 2-IN
                 ( L-B    2-IN )
                 5 STRAP  2-IN
                 1 HUB    2-IN


\ 300A 350MCM  2-1/2
                15 ALRC   2-1/2
                54 THHN   350mcm
                 3 NUT    Big-Blue
                 1 W-H    2-1/2
                 1 NT-CON 2-1/2
                 ( L-B    2-1/2 )
                 5 STRAP  2-1/2
                 1 HUB    2-1/2


get nt-con
get strap                                              0.00     0.00        0.00
get hub                                                0.00     0.00        0.00


\ 280A-3P  300MCM 3-IN  (Out of date)
Lower portion    10 ALRC       3-IN
Top portion       5 GRS        3-IN
Steel please      1 Coupling   3-IN
Copper           15 3 + 4 * THHN 300MCM
Less if roof      1 W-H        3-IN
Same as lugs      3 KOUPLE-TAP 350-2/0
                  ( NT-CON     3-IN
                  ( L-B        3-IN
Or strut          5 STRAP      3-IN
                  1 HUB        3-IN


\ 380A 500MCM 3-IN      (Out of date)
                15 ALRC       3-IN
                54 THHN       500MCM
                 1 W-H        3-IN
                 3 KOUPLE-TAP 500-4
                 1 NT-CON     3-IN
                 ( L-B        3-IN
                 5 STRAP      3-IN
                 1 HUB        3-IN


\ 420A 600MCM 3-IN      (Out of date)
                15 ALRC       3-IN
                54 THHN       600MCM
                 1 W-H        3-IN
                 3 KOUPLE-TAP 500-4
                 1 NT-CON     3-IN
                 ( L-B        3-IN
                 5 STRAP      3-IN
                 1 HUB        3-IN


200A 3/0 2-in 3P        (Out of date)
                15 ALRC   2-in                       127.20     1.50      307.20
                17 4 *  THHN 3/0                     473.28     1.76      684.48
                 4 NUT    Big-Blue                     1.80     0.16       21.00
                 1 W-H    2-in                        37.52     1.40      205.52
                 1 NT-CON 2-in                        43.00     0.40       91.00
                 ( L-B    2-in                         0.00     0.00        0.00
                 5 STRAP  2-in                        11.80     0.05       17.80
                 1 HUB    2-in                        12.00     0.65       90.00
                                                    $706.60     5.92   $1,417.00

380A 500MCM 3-IN   2-8-2012 Our Planet Earth
                15 ALRC       3-IN                   230.55     2.10      482.55
                54 15 + THHN       500MCM            657.57     3.03    1,021.17
                 1 W-H        3-IN                   133.24     1.80      349.24
                 1 NT-CON     3-IN                   172.05     0.75      262.05
If needed        1 L-B        3-IN                   115.58     3.25      505.58
                 5 STRAP      3-IN                    19.60     0.05       25.60
                 1 HUB        3-IN                    24.00     0.65      102.00
                                                  $1,352.59    11.63   $2,748.19

Total Estimate                                                         $4,676.72

