Various romex methods
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                



\ Blow no longer true
\ New PVC Cut-pay to 35
Low Rate !!     \ 35.00 per-hour
New construction ( with plans,
Clear, clean,    ( no trades, framed )
No installing    ( or hanging fixtures )
No lamps
No Permit fees   15 romex  14/2
                 ( 3 romex  staple
Broom swept      1 pvc-box 1g
Time for us      1 device pr
No indecision    1 plate pr


get romex
get plate                                                       0.00        0.00
get pvc-box                                                     0.00        0.00


New PVC Standard
Was 50.00 HR    137.00 per-hour                                 0.00        0.00
Brand new                                                       0.00        0.00
construction                                                    0.00        0.00
with plans,                                                     0.00        0.00
clear, clean,                                                   0.00        0.00
Some trades                                                     0.00        0.00
Some changes                                                    0.00        0.00
Home owner      15 romex  14/2                                  0.31       48.17
Out of town GC   1 pvc-box 1g                                   0.30       41.68
Vents in         1 device pr                                    0.10       15.70
HVAC drawn       1 plate pr                                     0.03        4.77
                                                                0.74     $110.32

New 4S+ Custom 50
Remodeling      \ 50.00 per-hour                                0.00        0.00
No plans,                                                       0.00        0.00
clear, clean,                                                   0.00        0.00
Plumber started                                                 0.00        0.00
framed.                                                         0.00        0.00
Owner thinking  15 romex  14/2                                  0.31       48.17
Changes          ( romex  staple                                0.00        0.00
Original walls   1 4s vb                                        0.30       42.70
No plans         1 4s-1g 5/8                                    0.15       22.31
                 1 device pr                                    0.10       15.70
                 1 plate pr                                     0.03        4.77
                                                                0.89     $133.65

New 4S+ Tract 35
Good plans,     \ 35.00 per-hour                                0.00        0.00
clear, clean,                                                   0.00        0.00
Plumber done                                                    0.00        0.00
framed.                                                         0.00        0.00
No changes                                                      0.00        0.00
                15 romex  14/2                                  0.31       48.17
                 ( romex  staple                                0.00        0.00
                 1 4s vb                                        0.30       42.70
                 1 4s-1g 5/8                                    0.15       22.31
                 1 device pr                                    0.10       15.70
                 1 plate pr                                     0.03        4.77
                                                                0.89     $133.65

New 4S+ Rough only
Good plans,     ( Use 2/3 the time  0.54 hrs )                  0.00        0.00
clear, clean,                                                   0.00        0.00
Plumber done                                                    0.00        0.00
framed.                                                         0.00        0.00
No changes                                                      0.00        0.00
                15 romex  12/2                                  0.37       59.09
                 ( romex  staple                                0.00        0.00
                 1 4s vb                                        0.30       42.70
                 1 4s-1g 5/8                                    0.15       22.31
                                                                0.82     $124.10

Upper 1/2 Fish & Trim
                 1.00 SW-Box cut-in                             0.42       61.54
                 1.00 Secure F-strap                            0.03        4.51
                 4.00 Romex  14/2                               0.08       12.48
In baseboard     1.00 Blockage Plate                            0.75      102.75
                                                                1.28     $181.28

The trim work    Elect
                 1 Device PR                                    0.10       15.70
                 1 Plate PR                                     0.03        4.77
                                                                0.13      $20.47

Lower 1/2 8-ft lower have to use EMT
Open joists     ( can't use romex below 8-ft )                  0.00        0.00


54              \ 54.00 per-hour
1/2 of 18        9.00 emt 1/2                                   0.40       59.84
                 0.75 4s box                                    0.22       31.16
                 1.00 romex blue                                0.11       15.59
                 0.75 4s bl                                     0.12       17.44
                 0.75 ground GS                                 0.03        4.19
3/4 of 2         1.50 ss-con 1/2                                0.12       16.80
                 0.75 ss-coup 1/2                               0.03        4.33
4.83 f 36       18.00 thhn #12                                  0.10       20.54
1/2 of 6         3.00 nut red                                   0.18       24.99
                                                                1.31     $194.88

Lower 1/2 8-ft +high Rx Ok


Can use romex   ( drill the joists or fish )
52               52.00 per-hour                                 0.00        0.00
1/2 of 18        7.00 emt 1/2                                   0.31       20.04
                 0.55 4s box                                    0.16        9.06
                 1.00 romex blue                                0.11        6.24
                 0.55 4s bl                                     0.08        4.89
                 0.50 ground GS                                 0.02        1.09
3/4 of 2          .75 ss-con 1/2                                0.06        3.30
                 0.45 ss-coup 1/2                               0.01        0.65
4.83 f 36       10.00 thhn #12                                  0.06        6.92
1/2 of 6         2.00 nut red                                   0.12        6.46
                                                                0.93      $58.65

Basement lath  Both
XX               \ 106.00 per-hour                              0.00        0.00
Fish down to the 5 romex  14/2                                  0.10        7.10
EMT below        1 sw-box cut-in                                0.42       25.84
over a basement  1 secure f-strap                               0.03        1.96
that has lath    1 device pr                                    0.10        7.20
and plaster on   1 plate  pr                                    0.03        2.22
                 1 blockage plate                               0.75       39.00
the ceiling     10 emt 1/2                                      0.45       29.00
                0.50 4s box ( 1 romex blue                      0.15        8.48
                 1 4s bl   1 ground GS                          0.20       11.85
                 2 ss-con 1/2                                   0.16        8.80
                 1 ss-coup 1/2                                  0.04        2.38
                 4 nailer 1/2                                   0.04        3.20
                30 thhn #12                                     0.18       20.76
                 4 nut red                                      0.24       12.92
                                                                2.89     $180.71

Basement 8-ft plus & open


                25 romex  14/2
                1  sw-box cut-in                                0.42       25.84
                1  secure f-strap                               0.03        1.96
                1  device pr                                    0.10        7.20
                1  plate  pr                                    0.03        2.22
                0.50 4s box                                     0.15        8.48
                0.50 4s bl                                      0.08        4.83
                2 rx blue                                       0.22       12.48
                                                                1.03      $63.01

Running boards, Ez hight


                25 romex  14/2
                1  sw-box cut-in                                0.42       25.84
Or #4 FHWS      1  secure f-strap                               0.03        1.96
                1  device pr                                    0.10        7.20
                1  plate  pr                                    0.03        2.22
Running board   15 minutes electrician                          0.25       13.00
The wood        5 dollars parts                                 0.00       10.00
Head hight EZ                                                   0.00        0.00
                1 rx blue                                       0.11        6.24
                                                                0.94      $66.46

LT above the switch
Fished LT       ( in plaster with NO blocks )                   0.00        0.00
                7 romex  14/2                                   0.14        9.94
                1  4-oct box                                    0.40       22.95
                2  bar-hanger 18-in                             0.40       27.24
                1  device pr                                    0.10        7.20
                1  Plate pr                                     0.03        2.22
                                                                1.07      $69.55

Fished plaster Regular
Fished outlet   ( in plaster walls )                            0.00        0.00
                \ 35.00 per-hour                                0.00        0.00
                 2 Blockage Fire-block                          0.90       46.80
                 1 Blockage Floor-plate                         0.75       39.00
                15 Romex  14/2                                  0.31       21.82
                 1 SW-box cut-in                                0.42       25.84
                 2 Secure F-strap                               0.06        3.92
                 1 Device pr                                    0.10        7.20
                 1 Plate  pr                                    0.03        2.22
                                                                2.57     $146.80

get sw-box
get secure                                                      0.00        0.00


Fished plaster Medium
Fished outlet                                                   0.00        0.00
in plaster                                                      0.00        0.00
walls with                                                      0.00        0.00
blocks                                                          0.00        0.00
                 1 Blockage   Fire-block                        0.45       23.40
                 1 Blockage   Plate-easy                        0.50       26.00
                15 Romex  12/2                                  0.37       27.64
                 1 SW-box cut-in                                0.42       25.84
                 2 Secure f-strap                               0.06        3.92
                 1 Device pr                                    0.10        7.20
                 1 Plate  pr                                    0.03        2.22
Adjustment      -0.18 HR EL                                    -0.19       -9.88
                                                                1.74     $106.34

                ( 08-13-07 JAP )


SW Back to back
In Lath                                                         0.00        0.00
Retail          3  romex  14/2                                  0.06        4.26
                1  sw-box cut-in                                0.42       25.84
                2  secure f-strap                               0.06        3.92
                1  device pr                                    0.10        7.20
                1  plate  pr                                    0.03        2.22
                                                                0.67      $43.44

PR Back to back
In baseboard                                                    0.00        0.00
                3  romex  14/2                                  0.06        4.26
                1  sw-box cut-in                                0.42       25.84
                2  secure f-strap                               0.06        3.92
                1  device pr                                    0.10        7.20
                1  plate  pr                                    0.03        2.22
                                                                0.67      $43.44

\ 1/2-Open walls
ROMEX  1/2 open
walls no blocks
trdes or
not vacant.
                15 romex  14-2
                1  sw-box vb
                1  device pr
                1  plate  pr


\ Big holes OK
ROMEX  Big
holes OK or 1/2
open walls no
blocks
                15 romex  14-2
                1  sw-box vb
                1  blockage stud
                1  device pr
                1  plate  pr


\ Run home 50 ft.
Run home with
romex in new
work, clear
area, CP/M.
                50 romex 14/2
                2 romex blue


\ SW-ed
Cost of 14-3
less cost 14-2
                 15 romex 14/3
                -15 romex 14/2


\ Split fish only
Fished outlet
ready for
tie in later
No trim
included at
this time )
                15 romex  14/2
                1 blockage  stud
                1  sw-box cut-in
                1  permit outlet


Split Rx Trim
Just secure                                                     0.00        0.00
cutin box                                                       0.00        0.00
and finish                                                      0.00        0.00
                1  device pr                                    0.10        7.20
                1  plate pr                                     0.03        2.22
                                                                0.13       $9.42

Split Make (J)
Just tie in                                                     0.00        0.00
lower part                                                      0.00        0.00
of fished                                                       0.00        0.00
                1 romex blue
                2 nut red


Smoke 110 volt
                7 romex 14-2
                2 romex blue
                1 3-oct tiger
                1 fixture smoke
                1 blockage easy
                1 permit outlet
                1 setup apartment


\ RX ( Prices  Mass production )   SAFECO!  AC-5
Vocabulary RX RX definitions \   See scr two
\ See also screen 38 (Normal)    \  MOVED TO NEW
: 14-2  (  60.00 )  12 ex 27 m ; \ SAFECO


\ 12-2  (        )  33 ex 30 m ; \
\ 14-3  (        )  49 ex 30 m ; \
\ 12-3  (        )  67 ex 35 m ; \


: BOX    ( .29 ? )  65 EX 25 C ; \ PayPac  AR-3
: PLUG   ( .85   ) 153 EX 15 C ; \ SAFECO  E-3
: COVER  ( .16   )  32 EX 00 C ; \ SAFECO  D-9
: STAPLE            01 EX 00 C ; \
Electric definitions


Short fish ez    7.14   1.47 hrs @ $47 = $76.2
Fished outlet
in plaster
walls with
                5  romex  14/2
                1  sw-box cut-in
                1  secure f-strap
                1  device pr
                1  cover  pr
                1  permit outlet
                1 blockage   fire-block
                0 blockage   plate


Un striped rx blue    3.01         0.78
                3 romex blue
                1 device pr
                1 cover pr
                10 minutes electrician


PVC box only          0.51 w/e      0.30 hrs
                1 pvc-box 1g


Cut-in only           3.07
                1 SW-BOX CUT-IN
                1 device pr
                1 plate pr


4S Box only           3.07 w/e      0.67 hrs
                1 4s vb
                2 rx blue
                1 4s-1g 1/2
                0 device pr
                0 plate pr


Dryer Rx & EMT       55.51
                50 rx 10/3
                20 emt 1/2
                3 4s box
                1 c-b 30a
                20 3 * thhn #10
                1 device-220 dryer
                6 nut red
                4 ss-con 1/2
                2 rx medium
                1 4s-ind 1-9/16
                2 4s bl
                5 strap 1/2


Runs              1,137.00 1,
15A             100 rx 14/2
15A             100 rx 14/3
20A             100 rx 12/2
20A             100 rx 12/3
30A             100 rx 10/3
50A             100 rx  8/3
65A             100 rx  6/3
85A             100 rx  4/3
115A            100 rx  2/3                   1


Range top Rx
                Open-2x4
                40 rx 10/3
                2 blue medium
                1 4s vb
                1 4s-2g 1/2
Hookup whip     15 minutes electrician
                1 c-b 30a
                1 mc-con 1/2


Dryer Open Romex
                50 rx 10/3
                1 4s vb
                1 c-b 30a
                1 device-220 dryer
                2 rx medium
                1 4s-1g 1/2
                1 Plate-SS dryer


Range Open Romex
                50 rx 6/3
                1 4s vb
                1 c-b 50a
                1 device-220 Range
                2 rx medium
                1 4s-1g 1/2
                1 Plate-ss dryer


PL over bsement
                 106.00 per-hour
Fish down to the 4 romex  14/2
EMT below        1 sw-box cut-in
Over a basement  1 secure f-strap
that has lath    1 device pr
and plaster on   1 plate  pr
                 1 blockage floor-plate
the ceiling      5 emt 1/2
                 1 4s box
                 1 romex blue
                 1 4s bl    1 ground GS
                 2 ss-con 1/2  1 ss-coup 1/2
                 3 nailer 1/2
                30 thhn #12
                 2 nut red


PL down from attic
                 106.00 per-hour
                 1 blockage floor-plate
                 1 blockage fire-block
Fish down        27 romex  14/2
EMT below        1 sw-box cut-in
Over a basement  1 secure f-strap
                 2 romex blue
that has lath    1 device pr
and plaster on   1 plate  pr
                 2 nut red


\ get stuff


get rx
get sw-box
get secure
get plate
get blockage
get 4s
get ss-con
get ss-coup
get nailer
get nut
get blockage
free



