                                                      15mar87jap
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LF-ROMEX #14-2  26.94 + 3.94 hrs @ $47 = $212.12    15mar87jap
\ LF-RUN with romex in new work,                                
\ clear area, CP                                                
100 romex 14-2                                  189         3.50
50 romex staple                                 000             
4 romex blue                                    022         0.44
( 4 because runs are usually 50 feet )                          
Total                                                           
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LF-ROMEX #14-3  51.02 + 4.48 hrs @ $47 = $261.58              
.( LF-RUN with romex in new work, )                             
.( clear area, CP/M. ) cr cr                                    
100 romex 14-3                                  237         4.00
50 romex staple                                 000             
4 romex medium                                  024         0.48
( 4 because runs are usually 50 feet )                          
Total                                                           
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LF-ROMEX #12-2  34.94 + 4.94 hrs @ $47 = $267.12              
\ LF-RUN with romex in new work,                                
\ clear area, CP/M. ) cr cr                                     
100 romex 12-2                                  244         4.50
50 romex staple                                 000             
4 romex blue                                    022         0.44
( 4 because runs are usually 50 feet )                          
Total                                                           
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LF-ROMEX #12-3  69.02 + 4.98 hrs @ $47 = $303.08              
\ LF-RUN with romex in new work,                                
\ clear area, CP/M. ) cr cr                                     
100 romex 12-3                                  278         4.50
50 romex staple                                 000             
4 romex medium                                  024         0.48
( 4 because runs are usually 50 feet )                          
Total                                                           
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LF-ROMEX #10-3 106.02 + 5.48 hrs @ $47 = $363.58              
\ LF-RUN with romex in new work,                                
\ clear area, CP/M. ) cr cr                                     
100 romex 10-3                                  339         5.00
50 romex staple                                 000             
4 romex medium                                  024         0.48
\ 4 because runs are usually 50 feet )                          
Total                                                           
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ LF-ROMEX #8-3  220.30 + 6.52 hrs @ $47 = $526.74              
\ LF-RUN with romex in new work,                                
\ clear area, CP/M. ) cr cr                                     
100 romex 8-3                                   500         6.00
50 romex staple                                 000             
 4 romex lg-blue                                026         0.52
\ 4 romex 2s-con 3/4                                            
( 4 because runs are usually 50 feet )                          
Total   \ The 2s-con wont fit                                   
        \  till I get NEEDs on a Clone                          
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


