                                                      03feb87jap
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 100 Empty 1/2   55.23 + 7.23 hrs @ $47 =  $395.23   03feb87jap
.(      100 feet 1/2" EMT with 2-#12 copper inc tails )   cr    
   100 emt 1/2                                                  
\  200 THHN #12                                                 
    25 NAILER 1/2                                               
    11 RT-COUP 1/2                                              
TOTAL                                                           
cr .(             Divide by one hundred for the LF price  )     
 cr                                                             
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 100 20A 1/2     79.23 + 8.42 hrs @ $47 =  $475.23   03feb87jap
.(      100 feet 1/2" EMT with 2-#12 copper inc tails )   cr    
   100 emt 1/2                                                  
   200 THHN #12                                                 
    25 NAILER 1/2                                               
    11 RT-COUP 1/2                                              
TOTAL                                                           
cr .(             Divide by one hundred for the LF price  )     
 cr                                                             
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 100 30A 1/2    130.23 + 9.61 hrs @ $47 =  $582.23   03feb87jap
100 EMT 1/2                                                     
300 THHN #10                                                    
11 RT-COUP 1/2                                                  
25 NAILER 1/2                                                   
TOTAL                                                           
\S                                                              
\ 2 RT-CON                                                      
\ WIRE TAILS                                                    
\ BENDS                                                         
\ WALLS                                                         
\ PERMINT                                                       
\ OBSTRUCTIONS                                                  
                                                                
                                                                
                                                                


\ 100 50A 1/2    178.23 + 10.23 hrs @ $47 =  $659.23  03feb87jap
100 EMT 1/2                                                     
300 THHN #8                                                     
11 RT-COUP 1/2                                                  
25 NAILER 1/2                                                   
TOTAL                                                           
\S                                                              
\ 2 RT-CON                                                      
\ WIRE TAILS                                                    
\ BENDS                                                         
\ WALLS                                                         
\ PERMINT                                                       
\ OBSTRUCTIONS                                                  
                                                                
                                                                
                                                                


\ 100 65A 3/4    248.73 + 12.38 hrs @ $47 =  $830.73  03feb87jap
100 EMT 3/4                                                     
300 THHN #6                                                     
11 RT-COUP 3/4                                                  
15 STRAP 3/4                                                    
                                                                
TOTAL  \S                                                       
\ 2 RT-CON                                                      
\ WIRE TAILS                                                    
\ BENDS                                                         
\ WALLS                                                         
\ PERMINT                                                       
\ OBSTRUCTIONS                                                  
                                                                
                                                                
                                                                


\ 100 85A 1-IN   392.34 + 15.57 hrs @ $47 =  $1124.34 03feb87jap
100 EMT 1-IN                                                    
300 THHN #4                                                     
11 RT-COUP 1-IN                                                 
15 STRAP 1-IN                                                   
                                                                
TOTAL  \S                                                       
\ 2 RT-CON                                                      
\ WIRE TAILS                                                    
\ BENDS                                                         
\ WALLS                                                         
\ PERMINT                                                       
\ OBSTRUCTIONS                                                  
                                                                
                                                                
                                                                


\ 100 85A 1-1/4  445.50 + 18.17 hrs @ $47 =  $1299.50 03feb87jap
100 EMT 1-1/4                                                   
300 THHN #4                                                     
11 RT-COUP 1-1/4                                                
15 STRAP 1-1/4                                                  
                                                                
TOTAL  \S                                                       
\ 2 RT-CON                                                      
\ WIRE TAILS                                                    
\ BENDS                                                         
\ WALLS                                                         
\ PERMINT                                                       
\ OBSTRUCTIONS                                                  
                                                                
                                                                
                                                                


\ 100 115A 1-IN  608.34 + 16.76 hrs @ $47 =  $1396.34 03feb87jap
100 EMT     1-IN                                                
300 THHN    #2                                                  
11  RT-COUP 1-IN                                                
15  STRAP   1-IN                                                
                                                                
\ TOTAL  \S                                                     
\ 2 RT-CON                                                      
1 C-B       100A    ( Tennant disconnect )      097             
1 PANEL     125a-12-24 ( Spaces )               167             
1 GROUND    100A    ( 8 ft rod and to water )   097             
1 PERMIT    SERVICE ( City inspection fees )    003             
1 BOND      H20     ( Ground Hot, Cold, Gas )   041             
                                                                
\ Service        364.74  16.25 hrs @ $47 = $1,128.49  17apr87jap
                                                                


\ 100 150A 1-1/4 946.50 + 20.57 hrs @ $47 =  $1913.50 03feb87jap
100 EMT     1-1/4                                               
300 THHN    1/0                                                 
11  RT-COUP 1-1/4                                               
15  STRAP   1-1/4                                               
                                                                
\ TOTAL  \S                                                     
\ 2 RT-CON                                                      
\ WIRE TAILS                                                    
\ BENDS                                                         
\ WALLS                                                         
\ PERMINT                                                       
\ OBSTRUCTIONS                                                  
                                                                
                                                                
                                                                


\ 100 200A       1290.20 + 23.38 hrs @ $47 = $2389.20 03feb87jap
100 EMT 1-1/2                                                   
300 THHN 3/0                                                    
11 RT-COUP 1-1/2                                                
15 STRAP 1-1/2                                                  
                                                                
TOTAL  \S                                                       
\ 2 RT-CON                                                      
\ WIRE TAILS                                                    
\ BENDS                                                         
\ WALLS                                                         
\ PERMINT                                                       
\ OBSTRUCTIONS                                                  
                                                                
                                                                
                                                                


RT-BOX vs LB          4.62 w.s.     1.50 hrs     81.23          
                1 rt-box 2x4-4hub                81.23    81.23 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


RT-BOX vs LB          3.88 w.s.     0.50 hrs     30.23          
                1 l-b 1/2                        30.23    30.23 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


