                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


                    273.32 Parts   56.88 hrs    273.32          
                Wholesale                                       
                240 187 - rx blue                10.60          
                13 3 - l-b 1/2                   38.80          
                10 3 - ss-90 1/2                 12.74          
                6 3 - l-b 1/2-ent                11.64          
                50 24 - sw-box cut-in            37.18          
                23 10 - 3-oct tiger              15.60          
                6 3 - alrc-90 1-1/4              24.60          
                27 6 gr-bush 1-1/4               13.08          
                49 30 - device pr ( white )      16.15          
                33 25 - device sw                 5.20          
                8 4 - wm-box 5738a               15.48          
                345 100 - ground gs              12.25          
                30 10 - c-b 15a                  60.00   273.32 
                                                                


                    423.87 Parts   48.41 hrs    423.87          
                8 4 - lug 1/0                                   
                4 1 - rt-box 5-hub               17.70          
                244 150 - ss-con 1/2             18.80          
                27 12 - strap-2-rigid                           
                77 30 - 4s box                   65.80          
                68 25 - secure toggle            10.75          
                4 2 - c-b 50a                    25.10          
                2 1 - lo-volt 16-volt             6.50          
                5565 4000 - thhn #12             93.90          
                30 12 - c-b 20a                  54.00          
                3 2 - rt-plate 4x4-bl             1.36          
                8 4 - rt-plate 2x4-bl             3.44          
                1 halo h27t                      13.93          
                3 fan light-fan                 112.59   423.87 
                                                                


                    139.95 Parts    3.80 hrs    139.95          
                8 3 - halo h-7                  109.25          
                80 20 - secure f-strap           12.00          
                64 9 - ko-fill 3/4               18.70   139.95 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Totals              837.14        109.09        837.14          
                                                     ========== 
                                                         837.14 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


