Smoke alarms                                        08-30-90 AL
Broadway Associates                                1245 Broadway
1245 Broadway                                   Hide/Leavenworth
San Francisco, CA 94109                             Bob 928-8184
                                                      W 768-3638
                                                    Ref: History
                                                 61.43 Direct hr
                                                  5.11 Team Days
                                              1,181.46 Pre costs
                                              5,317.15 Total Bid
                   October 22, 1990              81.91 Total hrs
                                                  8.60 Set clean
                     TESTING DONE                20.47 Bid & etc
                                                 45.00 Insp fees
We earn our references and repeat business.       0.00 Risk Ins.
                                                                


City permit fees     45.00 w.s.     1.05 hrs    113.22          
Be Inspected     1 Appointment Meet-Inspector    37.50          
Filing fee       1 Permit Filing                 45.37          
Smoke            2 Permit Smoke                   4.72          
Electronics      1 permit Control-panel           7.76          
Break glass      1 permit pull-station            6.07          
Heat             5 permit detector               11.80          
.                                                        113.22 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Prerequsites          0.00 w.s.     8.60 hrs    430.00          
Mobilization    1 Setup Equipment-Site          150.00          
Lots of stairs  3 hours Electrician             150.00          
Hall carpets    2 hours Electrician             100.00   430.00 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Contingencies         0.00 w.s.     0.00 hrs      0.00          
Halls only      00 Dollars Allowance                       0.00 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Risk Insurance      150.00 w.s.     0.00 hrs    150.00          
See PP #16     150 Dollars Allowance            150.00   150.00 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Typical Unit         13.65 w.s.     2.85 hrs    160.92          
                Fish-in-walls                                   
Ceiling         LT-medium                       108.30          
                1 Fixture Smoke                  15.12          
Clean and       1 setup apartment                37.50          
.                                                               
.                                                               
.                                                               
.                                                               
.                                                        160.92 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


5 more units         81.90 w.s.    17.10 hrs    965.52          
                Fish-in-walls                                   
Ceiling 2       LT-medium                       108.30          
                1 Fixture Smoke                  15.12          
Ceiling 3       LT-medium                       108.30          
                1 Fixture Smoke                  15.12          
Ceiling 4       LT-medium                       108.30          
                1 Fixture Smoke                  15.12          
Ceiling 5       LT-medium                       108.30          
                1 Fixture Smoke                  15.12          
Ceiling 6       2 LT-medium                     216.60          
                2 Fixture Smoke                  30.24          
Vacume clean    6 setup apartment               225.00   965.52 
                                                                
                                                                
                                                                


Hall smoke EMT      223.60 w.s.    27.80 hrs  1,613.60          
                Neat-EMT                                        
Power for unit  Outlet                          117.20          
Mount in wall   2 hours Electrician             100.00          
Pull station    PL                              107.20          
4 bells         4 LT                            468.80          
2 smokes        2 LT                            234.40          
Heat detectors  5 LT                            586.00 1,613.60 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


House Panel          49.55 w.s.     3.06 hrs    219.89          
                Neat-EMT                                        
                1 panel 125a-8-16               114.15          
For electronics 1 c-b 30a                        36.94          
Existing        1 c-b 15a                        15.40          
Existing        1 c-b 20a                        15.40          
Relocate trans  15 minutes Electrician           12.50          
Relocate switch 30 minutes Electrician           25.50   219.89 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Hall Electronics    600.00 w.s.     4.40 hrs  1,030.00          
                1 Fire Supervisor               538.75          
                4 Fire Bell-10in                121.00          
                2 Fire Smoke                    168.50          
                1 Fire Pull-Station              43.75          
                5 fire Heat                     158.00 1,030.00 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Testing               0.00 +Tax     6.13 hrs    306.50          
Chris           2 Hours Chris                    73.00          
Jim             2 Hours Jim                      40.00          
JP              2 Hours JP                      129.00          
Teach locals    1 hour JP                        64.50   306.50 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Thermostat            8.50 w.s.     1.80 hrs    101.00          
Up 2 floors     50 wire 18/3                     51.00          
Carefull thru   1 hour  Electrician              50.00   101.00 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Hall Plug             6.26 w.s.     2.75 hrs    145.95          
                Fish-in-wall                                    
                PL                              145.95   145.95 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Other                 3.00 w.s.     7.66 hrs    387.05          
Super neat      17 Setup Tarps ( Cover-floor)   297.50          
Setup plaster   30 minutes Electrician           25.50          
Smooth plaster   3 Plaster Medium ( Incision)    64.05          
.                                                               
.                                                               
.                                                               
.                                                               
.                                                        387.05 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Totals            1,181.46         81.91      5,559.15          
                                                     ========== 
PAY SCHEDULE                Contract price package     5,559.15 
                                        or           ========== 
10% Binder               Without a contingency fund of   -50.00 
                      and with a discount you can earn   -69.00 
80% Rough-in                  Discounted item Total    5,198.15 
.                                                               
10% Final Insp.  Owner's punch list due within 24 hours         
.                                                               
.                                                               
                                                                
                                                                
                                                                
                                                                
                                                                


Earn a discount                                                 
Please help us and these savings are yours.                     
Telephone me with this paper in front of you      7.00          
Audit contract details on the phone with me.     17.00          
Be present the first hour to confirm details.     9.00-no       
Discount for having a 24 hr fax machine.          7.00          
Provide a set of keys for duration of job.        7.00          
Let us use the job phone for business calls.      7.00          
Wait till we finish the job ahead of yours.      17.00          
Make a progress payment on site each week.        7.00          
                                                 ------         
                                                 69.00          
                                                                
                                                                
                                                                
                                                                


NIC= Not Included                                               
Attic work in insulation                            NIC         
We offer Telephone, Cable TV, & music wireing       NIC         
Concealed or unseen work that may be discovered     NIC         
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


We charge extra                                                 
Reinspections "I hope the inspector doesn't see it" ($86.00)    
Missing keys, lock outs or cancelations after start (100.00)    
                                                                
Time spent discussing, prices and charges for changes involving 
work already in progress will be billed even if the changes are 
not accepted.  Late changes are awfull for everyone.            
                                                                
Our rates are: $50.00 per manhour which include wages, insurance
taxes, engineering, supervision, owner's sallary & profit share.
Parts are wholesale + Tax + 15% overhead + 10% profit.          
15% sircharge on glass light bulbs, tubes & dimmers (attrition) 
                                                                
                                                                
                                                                
                                                                


Contingencies inc.                                              
NOTE: Use of this fund will be invoiced after the fact.         
.                                                               
Try to spend some dimes that will save you dollars.             
Correct a minor code problem or hazzard.                        
Do some litle extra thing the inspector recommends.             
Clean up a code problem while working in the same area.         
Handle minor maintenance or repairs.                            
Replace a inferior device or cover plate etc.                   
Take the time to do a better job than is called for.            
Let you stop us mid task about changes (Kills inertia)          
Take time to explain the details we are handeline for you.      
Invistigate any reports of non working electrical devices       
Try to make you happy to hire us again.                         
                                                                
                                                                


Insured Risks 1                                                 
Used equipment quits "It always worked till your men got here"  
Tennants possesions or trades men's gear on site to guard.      
Working above people equipment or furnishings.                  
Aries is looked at as the expert.                               
You might count on us knowing something without telling us.     
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Statement                                           09-30-90 AEC
Agreement                                  4,300.55    4,300.55 
Retainer        Ck 690          Sep 25      -430.00    3,870.55 
Discount earned                              -69.00    3,801.55 
Panel                                        219.89    4,021.44 
Hall plug                                    150.00    4,171.44 
Paid Progress   Ck 0579         Oct 25    -3,500.00      671.44 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


