Set Screw EMT without wires but inc fittings.       88-05-01 AEC
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


: 1/2                42.57 w/e     4.50 c ; \  254.07           
                100 EMT 1/2                       243           
                11 SS-COUP 1/2                      4           
                25 NAILER 1/2                       6      253  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


: 3/4                58.96 w/e     5.50 c ; \  317.46           
                100 EMT 3/4                       303           
                11 SS-COUP 3/4                      6           
                25 NAILER 3/4                       7      316  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


: 1-in               92.16 w/e     7.00 c ; \  421.16           
                100 EMT 1-in                      397           
                11 SS-COUP 1-in                    11           
                25 NAILER 1-in                     12      420  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


: 1-1/4             116.35 w/e     8.50 c ; \  515.85           
                100 EMT 1-1/4                     495           
                11 SS-COUP 1-1/4                   20           
                25 NAILER 1-1/4                            515  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


: 1-1/2             141.70 w/e     9.00 c ; \  564.70           
                100 EMT 1-1/2                     535           
                11 SS-COUP 1-1/2                   29           
                25 NAILER 1-1/2                            564  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


: 2-in              192.80 w/e    11.00 c ; \  709.80           
                100 EMT 2-in                      658           
                11 SS-COUP 2-in                    39           
                25 STRAP  2-in                     12      709  
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ Automatically created code for the above modules  88-05-02 AEC
Vocabulary SS-EMT  SS-EMT Definitions                           
    : 1/2                42.57 w/e     4.50 c ; \  254.07       
    : 3/4                58.96 w/e     5.50 c ; \  317.46       
    : 1-in               92.16 w/e     7.00 c ; \  421.16       
    : 1-1/4             116.35 w/e     8.50 c ; \  515.85       
    : 1-1/2             141.70 w/e     9.00 c ; \  564.70       
    : 2-in              192.80 w/e    11.00 c ; \  709.80       
Electric definitions                                            
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


