Supports                                                        
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Hanger rod for Flo Fixt      2.04 +tax    0.34 hrs      20.41   
                1 secure hanger-bolt                            
Coupling        1 secure rod-coup                 2.81          
Four foot rod   4 secure rod-1/4                  7             
                1 conduit-hanger 3/4              5.47    20.41 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Hanger rod for 3/4 emt       2.04 +tax    0.34 hrs      20.41   
                1 secure hanger-bolt                            
Coupling        1 secure rod-coup                 2.81          
Four foot rod   4 secure rod-1/4                  7             
                1 conduit-hanger 3/4              5.47    20.41 
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


Chain Hung Only              
                 0 hang-flo 8-ft               
                20 support Jack-chain          
                 2 support S-hook              
                 2 support Bridal              
Or drill conc    4 support Eye-lag-conc        
Ladder                                         
Scaffolding                                    
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ SUPPORT  Chain-drop                                        AEC
SUPPORT definitions                                             
: Chain-drop    4.85 w/e       67 c ;                           
Elect                                                           
\S                                                              
                                                                
    46.58                                                       
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


