Wire molding                                                    
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ loader                                            07-29-89 AEC
Want w-m                                                        
                                                                
.( Wiremold parts cost a little more EMT )                      
.( but the labor is easier on the bends )                       
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                


\ 2 PR 10-ft run             
Raceway         10 W-M 500                     
2 Boxes         2 W-M 5747                     
Straps          5 W-M 504                      
Wire            35 THHN   #14                  
Plug            2 device  pr                   
Cover           2 plate   pr                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Ext 15-ft PR                 
Raceway         15 W-M 500                     
Flat 90          1 W-M 511                     
Box              1 W-M 5741                    
Ext box          1 W-M 5751                    
Straps           5 W-M 504                     
Wire            35 THHN #14                    
Plug             2 device PR                   
Covers           2 plate pr                    
                                               
                                               
                                               
                                               
                                               
                                               
                                               


\ WM Smoke                   
                2 w-m 500                      
                5 thhn #14                     
                3 nut yellow                   
                1 w-m 5737A  ( Med open )      
                1 W-M 5738   ( sml fixt )      
                1 w-m 504                      
                ( Device detector              
                1 permit incandescent          
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Ext & 2 PR 15-ft             
                1 W-M 5751                     
                15 W-M 500                     
                2 W-M 5747                     
Clips           4 W-M 504                      
                3 W-M device pr                
                3 W-M plate pr                 
                35 thhn #14                    
                4 nut yellow                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Corner adder                 
                1 W-M 517                      
                1 thhn #14                     
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Plug 10 ft                   
                1 device pr                    
                1 plate pr                     
Box             1 w-m 5748                     
Internal        1 w-m 5747                     
Hit clip        2 w-m 5703                     
                10 w-m 500                     
                10 3 * thhn #14                
                                               
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Plug 15 ft                   
                1 device pr                    
                1 plate pr                     
Box             1 w-m 5748                     
Internal        2 w-m 5747                     
Hit clip        4 w-m 5703                     
Raceway         15 w-m 500                     
Inc ground      15 3 * thhn #14                
Twisted         1 w-m 5711lh                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               


Plug 20 ft                   
                1 device pr                    
                1 plate pr                     
Box             1 w-m 5748                     
Internal        3 w-m 5747                     
Hit clip        4 w-m 5703                     
Raceway         20 w-m 500                     
Inc ground      20 3 * thhn #14                
Twisted         1 w-m 5711lh                   
                                               
                                               
                                               
                                               
                                               
                                               
                                               


